############################################
#' @title Diffusion Tube maps
############################################

#' @name tube.maps
#' @aliases tube.maps tubeMap leafletTubeMap
#' @description \code{DTEval} currently provides static \code{ggplot2} and
#' dynamic (html) \code{leaflet} diffusion tube maps.
#' @param data Data source to be used to build a plot. This is typically a
#' data.frame or similar, but can also be a previous plot generated by the
#' same function.
#' @param x,y The names of the data-series to plot on the
#' X and Y axes, respectively, and assumed to be sampling point longitude and
#' latitude.
#' @param plot.type The type of plot(s) to produce, e.g.:
#' \code{'point'} (default) for a scatter plot, \code{'surface'} to
#' fit a surface, etc...
#' @param ... Additional arguments. \code{tubeMap} uses \code{data}, \code{x},
#' \code{y} and optional argument \code{facet} to build map layers then passes
#' arguments on to \code{tubePlot} to generate plot layers.


# #' * \code{xlab}, \code{ylab} The X and Y axes labels to use if
# #' different from plot defaults.
# #'
# #'  * \code{group} The name of the data-series to use to group
# #'  plotted data with. By default, \code{ggplotTubeShell} assumes
# #'  supplied groups are factors if less than 20 unique cases.
# #'
# #'  * \code{facet} The name of the data-series to use to cut
# #'  the data by when generating multiple plot panels. Also provides
# #'  an addition \code{facet.type} shortcut to different \code{ggplot2}
# #'  facet options: \code{'wrap'} for \code{facet_wrap} (default),
# #'  \code{'grid'} for \code{facet_grid} (or 'grid.row' or grid.col' to
# #'  specific by row-then-column or column-then-row grid handling,
# #'  respectively).

#' @note
#' These functions are in development, so may change.


#' @return \code{tubeMap} generates static maps using \code{ggplot2}
#' and \code{OpenStreetMap}. \code{leafletTubeMap} generates interactive
#' (HTML) maps using \code{leaflet}.


#############################
# notes
#############################

# removed full imports
#    now always specifying directly in code, ggplot2::ggplot, etc
#    bit painful but some guessing some loading orders are generating conflicts

# don't use is.null(list(...)$facet), etc to test for facet
#    because it partial matches to longer facet... names if facet not there!!!
# same for groups, etc...



###########################
# tubeMap
###########################

# draw maps of tube locations

# notes
############################

# separated leaflet and ggplot2 versions
#   so this is just ggplot these days...

# thinking about
############################

# does tubeMap want a plot.type argument ??
# even if it is just to pass on to tubePlot ???
#      would make all the plot handling more consistent...

# think about this
# https://rud.is/b/2015/07/24/a-path-towards-easier-map-projection-machinations-with-ggplot2/

# looks like there are grid lines behind the maps
# looks like scale_x_continuous(breaks=NULL) and scale_x_continuous(breaks=NULL) will
#    fix this but it produces a waring...

# current test
#    dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
#    tubeMap(dd, facet=".year")

#' @rdname tube.maps
#' @export

tubeMap <-
  function(data, x=NULL, y=NULL, ...){

    #setup
    ####################
    .xargs <- list(...)
    if("ggplot" %in% class(data)){
      previous <- data
      d2 <- data$data
    } else {
      d2 <- data
      previous <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }

    #what to do about col/colour...?
    #   currently using this cludge in tubePlot
    #      and assuming colour hereafter...
    names(.xargs)[names(.xargs) %in% c("col", "color")] <- "colour"
    .xargs <- .xargs[!duplicated(names(.xargs), fromLast=TRUE)]
    if(is.null(x)){
      x <- ".longitude"
    }
    if(is.null(y)){
      y <- ".latitude"
    }

    d2 <- tagTubeRequired(d2, required=c(x, y, .xargs$facet))

    .x <- getTubeX(d2, x, if.err="stop<<tubeMap>>x")
    .y <- getTubeX(d2, y, if.err="stop<<tubeMap>>y")

    if(!"grid.borders" %in% names(.xargs)){
      .xargs$grid.borders <- 0.05
    }

    ##build map layer
    ###################
    if(is.null(previous)){
      #map ranges
      rng.lat <- range(.y, na.rm=TRUE)
      rng.lon <- range(.x, na.rm=TRUE)
      #adding border
      exp <- function(rng, n=0.1){
        temp <- (rng[2]-rng[1])*n
        c(rng[1]-temp, rng[2]+temp)
      }
      rng.lon <- exp(rng.lon, .xargs$grid.borders)
      rng.lat <- exp(rng.lat, .xargs$grid.borders)
      dc <- OpenStreetMap::openmap(c(rng.lat[2], rng.lon[1]),
                                   c(rng.lat[1],rng.lon[2]),
                                   zoom = NULL,
                                   type =  "esri",
                                   minNumTiles = 12,
                                   mergeTiles = TRUE)

      dc <- suppressMessages(suppressWarnings(
        OpenStreetMap::openproj(dc,
                                projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
      ))
      p1 <- dc$bbox$p1
      p2 <- dc$bbox$p2
      .bb <- data.frame(x = c(p1[1], p2[1]),
                        y = c(p1[2], p2[2]))
      names(.bb) <- c(x,y)
      if("facet" %in% names(.xargs)){
        .bb <- data.frame(.bb, facet=rep(unique(d2[[.xargs$facet]]), each=2))
        names(.bb)[3] <- .xargs$facet
      }
      #####################################
      # would like to simplify this bit...
      ######################################

      .all <- modifyList(list(data=d2, x=x, y=y), .xargs)
      # do I need to send all at this stage ???
      # would just data+x+y work to build the basic ggplot objects ???
      # test when this project has some quiet time ...
      plt <- suppressMessages(suppressWarnings(
        do.call(tubePlot, .all)
      ))
      .ggshell <- c("facet.type", "xlab", "ylab",
                    "auto.text", "palette", "fill.palette", "map.args",
                    "key.position", "key.direction", "rotate.x.axes")
      .xargs <- .xargs[!names(.xargs) %in% .ggshell]
      .xargs <- modifyList(list(x=x, y=y),
                           .xargs)

      for(tile in dc$tiles){
        p1 <- tile$bbox$p1
        p2 <- tile$bbox$p2
        rast <- matrix(tile$colorData, nrow = tile$xres, byrow = TRUE)
        plt <- plt + ggplot2::annotation_raster(rast, -Inf, Inf, -Inf, Inf,
                                                interpolate=TRUE)
      }

      plt <- plt + ggplot2::expand_limits(x = c(p1[1], p2[1]),
                                          y = c(p2[2], p1[2])) +
        ggplot2::scale_x_continuous(expand = c(0, 0)) +
        ggplot2::scale_y_continuous(expand = c(0, 0))

      ##########################
      # need to re-instate these
      #    (if we can stop them
      #     erroring out...)
      ##########################

      #dies of facetting...
      #plt <- plt + ggplot2::geom_label(x=rng.lon[2], y=rng.lat[1],
      #                                 label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                                 #fill="white", border.colour="white",
      #                                 #size=1.8,
      #                                  hjust=1, vjust=0.20, size=1.8, size.unit = "pc")

      #                      ggplot2::aes(x=x, y=y),
      #                      label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                      fill="white", border.colour="white",
      #                      size=1.8, hjust=1, vjust=0.20)

      #plt <- plt + ggplot2::coord_sf() + ggplot2::labs(x="") +
      #  ggplot2::labs(y="") +
      #  ggplot2::scale_x_discrete(labels = NULL, breaks = NULL) +
      #  ggplot2::scale_y_discrete(labels = NULL, breaks = NULL)


      map <- plt

      #      map + ggplot2::coord_equal()
      #################################
      # general map text, formatting and sizing
      #      suppressMessages(suppressWarnings(
      #        map <- plt + ggplot2::geom_text(data=data.frame(),
      #                                        ggplot2::aes(x=rng.lon[2], y=rng.lat[1]),
      #                                        label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                                        size=1.8, hjust=1, vjust=-0.5) #+
      #          ggplot2::coord_quickmap() +
      #          ggplot2::theme_void()
      #      ))
    } else {
      map <- previous
    }

    out <- suppressMessages(suppressWarnings(
      #tubePlot(map, x, y, ...) + ggplot2::coord_sf()
###############################
# test 
# tubePlot(map, x, y, ...) + ggplot2::geom_sf()
#   + coord_sf(crs = "WGS84"), st_crs(data), etc ...
# adding coord_sf(crs="WGS84") didn't fix it but it got me on the right track and I figured it out. 
# I changed the reference system for the EJRU object outside of the ggplot map code and then ran the code again.
###############################  
      tubePlot(map, x, y, ...) + ggplot2::coord_quickmap()
    ))


    out <- out + ggplot2::theme(axis.title.x=ggplot2::element_blank(),
                                axis.text.x=ggplot2::element_blank(),
                                axis.ticks.x=ggplot2::element_blank(),
                                axis.title.y=ggplot2::element_blank(),
                                axis.text.y=ggplot2::element_blank(),
                                axis.ticks.y=ggplot2::element_blank())
    out

  }








##############################
# leafletTubeMap
##############################

# draw maps of tubes using leaflet...

# separated leaftlet and ggplot2 versions of tubeMap 2025-09-18
#

# notes
##########################


# jobs
#############################

# current test
#    dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
#    leafletTubeMap(dd, point=T, polygon=dont.share::caz.bradford)
#    leafletTubeMap(dd, surface=T, point=T)

# standardize args and options so it is more like tubeMap

# add surface fit
#           see
#           https://stackoverflow.com/questions/67537458/creating-a-heatmap-on-r-using-leaflet-function-add-heatmap-or-addheatmap
#           https://gis.stackexchange.com/questions/168886/r-how-to-build-heatmap-with-the-leaflet-package

# leaflet
#   make a static copy of a leaflet output....
#      https://gis.stackexchange.com/questions/299192/saving-leaflet-map-as-image

# quick fix for quarto reports....
#  could not use leafletTubeMap in if in quarto


#' @rdname tube.maps
#' @export

# draw maps of tubes using leaflet...

leafletTubeMap <-
  function(data, x=NULL, y=NULL, plot.type=NULL, ...){

    #plot only intended for tagged or tag-able data...
    d2 <- data

    #args
    .xargs <- dte_ggshellTidyArgs(list(...))
    .xargs <- modifyList(list(grid.borders = 0.05,
                              auto.text = TRUE),
                         .xargs)

    if("leaflet" %in% class(data)){
      previous <- d2
      d2 <- data$dte_data
    } else {
      d2 <- data
      previous <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }
    #do we need/want tagging ?
    d2 <- tagTube(d2)

    ############################
    # x and y handling to enable
    ############################

    # avoiding %>%
    if(is.null(previous)){
      m <- leaflet::leaflet() |>
        leaflet::addProviderTiles("CartoDB.Positron")
      # yes, I am that lazy
      m$dte_data <- d2
    } else {
      m <- previous
    }

    ################################
    # plot.type like tubePlot
    #     BUT for selected plot types
    ################################
    #.check <- c("point", "line", "box", "band", "surface", "smooth", "polygon", "none", "ggsmooth")
    .check <- c("point", "surface", "polygon", "none")
    .tt <- c(plot.type, names(.xargs))
    for(i in .check){
      .tt[grepl(paste("^", i, "[.]", sep=""), .tt)] <- i
    }
    plot.type <- unique(.tt[.tt %in% .check])
    if(length(plot.type)==0){
      plot.type <- "point"
    }

    for(i in plot.type){

      if(i == "polygon"){
        ##########################
        # needs to track args
        ##########################
        if(!is.null(.xargs$polygon)){
          m <- leaflet::addPolygons(m, data=.xargs$polygon)
        }
      }

      if(i == "surface"){
        ##########################
        # currently needs raster added to imports
        #    see in-section notes...
        ##########################
        # needs to track args like point
        ##########################
        .fit.args <- modifyList(list(data=d2, tube=".value", inputs=c(".longitude", ".latitude"),
                                     new.data="input.ranges", simplify=TRUE),
                                #################################
                                # could generalise next bit ???
                                #################################
                                .xargs[names(.xargs) %in% c("too.far", "model",
                                                            "simplify",
                                                            "force.positive",
                                                            "grid.resolution",
                                                            "grid.borders")])

        .dd <- do.call(fitTubeModel, .fit.args)
#        .dd <- fitTubeModel(d2, tube=".value", inputs=c(".longitude", ".latitude"),
#                            new.data="input.ranges", simplify=TRUE, too.far=0.15,
#                            grid.borders=c(0.4), grid.resolution=300)
        #print(names(.dd))

        .lat <- unique(.dd$.latitude)
        .lon <- unique(.dd$.longitude)

        ##########################
        # raster package only used for next section of code at moment...
        #    like to remove that if possible... ???
        r <- raster::raster(xmn = min(.lon, na.rm=TRUE),
                    xmx = max(.lon, na.rm=TRUE),
                    ymn = min(.lat, na.rm=TRUE),
                    ymx = max(.lat, na.rm=TRUE),
                    nrows = length(.lon),
                    ncols = length(.lat))
        .mat <- matrix(.dd$.value.pred, nrow(r), ncol(r),
                       byrow = TRUE)
        .mat  <- .mat[c(ncol(.mat):1),,drop=FALSE]

        raster::values(r) <- .mat
        raster::crs(r) <- raster::crs("+init=epsg:4326")
        ################################
        #using leaflet::colorBin for blocked sacle
        pal <- leaflet::colorNumeric("Spectral", rev(pretty(.dd$.value.pred)),
                                     na.color = "#00000000", reverse=T)
        pal2 <- leaflet::colorNumeric("Spectral", rev(pretty(.dd$.value.pred)),
                                     reverse=F)
        m <- leaflet::addRasterImage(m, r, colors = pal, opacity = 0.3) |>
          leaflet::addLegend(pal = pal2, values = pretty(.dd$.value.pred),
                             labFormat = leaflet::labelFormat(transform = function(x) sort(x, decreasing = TRUE)))
        ############## contours
        .dd <- grDevices::contourLines(unique(.dd$.longitude), unique(.dd$.latitude), matrix(.dd$.value.pred, nrow=length(unique(.dd$.longitude))),
                                       level=c(1:6)*5)
        for(i in 1:length(.dd)){
          m <- leaflet::addPolylines(m, lng=.dd[[i]]$x, lat=.dd[[i]]$y, group=.dd[[i]]$level,
                                     label=.dd[[i]]$level)
          m <- leaflet::addLabelOnlyMarkers(m, lng=.dd[[i]]$x[1], lat=.dd[[i]]$y[1],
                                            group=.dd[[i]]$level[1],
                                     label=.dd[[i]]$level[1],
                                     labelOptions = leaflet::labelOptions(noHide = T, textOnly = F,
                                                                          textsize = "15px",
                                                                          style=list("color"="red"),
                                                                          direction="left"))
          #          data.frame(x=, y=.dd[[x]]$y, level=.dd[[x]]$level, grp=x)
        }
#        .dd <- do.call(rbind, .dd)
#        .dd <- .dd[.dd$level==20,]
#        print(.dd)
#        m <- leaflet::addPolylines(m, lng=.dd$x, lat=.dd$y, group=.dd$grp, noClip = T)


      }


      if(i == "point"){
        ##########################
        # tracking args 2
        #   IN_DEVELOPMENT
        #   thinking about tidying methods before doing for other plot.type(s)
        #      dte_ggshellTidyTestArgs to dte_localArgsTests because it can
        #             be used more generally ???
        #      dte_ggshellTidyTestArgs to dte_localArgsTidies
        #             could handle both,more...
        #   if this behaves, it could supersede the ggshell code completely... ???
        #   NEEDS color and radius mapping
        #   CAN'T do other shapes...
        # see re circle handling, popup, label, etc ...
        # https://rpubs.com/sofie/875527
        # https://rpubs.com/mayotunde/212634
        # also try leaflet::setView() to force starting position
        ##########################
        .xargs2 <- dte_localArgsTidies(.xargs, "point",
                                       tidy.name=list(c("col", "color"),
                                                      c("colour", "color"),
                                                      c("size", "radius")),
                                       tidy.ref=leaflet::addCircleMarkers)
        #needs a overplot stat handler like in tubePlot...
        #   guessing here ???
        #     see overplot in tubePlot, point...
        .xargs2.test <- dte_localArgsTests(.xargs2, d2)
        if(.xargs2$..test=="OK"){
          .xargs2 <- .xargs2[names(.xargs2) != "..test"]
          if("color" %in% names(.xargs2)){
            if(.xargs2.test$color=="data") {
              #########################
              #ONLY works for numeric at moment
              #needs palette control
              .xargs2$color <- leaflet::colorNumeric("Spectral",
                                  d2[[.xargs2$color]])(d2[[.xargs2$color]])
              #########################
              #needs a colour scale???
            }
          }
          .xargs2 <- modifyList(list(map=m, lng=d2$.longitude, lat=d2$.latitude,
                                     radius=2),
                                .xargs2)
          m <- do.call(leaflet::addCircleMarkers, .xargs2)
        }
      }
    ########################
    #end of for-loop
    }
    #end
    return(m)
  }






