############################################
#' @title Diffusion Tube Data Plots
############################################

#' @name tube.plots
#' @aliases tube.plots tubePlot tubeTimePlot
#' @description \code{DTEval} uses \code{ggplot2} to generate most plots.
#'
#' Obviously, you are welcome to use any graphics package you know to generate
#' your own plot. In fact, if you want really fine control of plot outputs, we
#' recommend taking the time to learn a graphics package like
#' \code{ggplot}, \code{lattice}, etc. But \code{DTEval} also includes
#' several quick-use wrappers for some commonly used plot types and useful
#' options like grouping and faceting, which can really help with data
#' visualisation. It also includes \code{tubePlot}, which builds
#' common plot shells for many of these, and handles some of of
#' the generic plot control for functions like \code{\link{testTubePrecision}}
#' and \code{\link{testTubePrecision}}.

# maybe link to ggplot2 and a r help page on graphics for this?

#' @param data Data source, typically a data.frame or similar, to be used to
#' build a plot using ggplot2.
#' @param x,y The names of the data-series to plot on the
#'  X and Y axes, respectively, and assumed to be elements of \code{data}.
#' @param plot.type The type of plot(s) to produce, e.g.:
#'  \code{'point'} (default) for a scatter plot, \code{'box'} for
#'  a box and whiskers plot, etc...
#' @param ... Additional arguments. See details below.

#' @details In addition to \code{data}, the main data source for
#' the plots, \code{tubePlot} also handles the following common
#' plot arguments:
#'
#' * \code{xlab}, \code{ylab} The X and Y axes labels to use if
#' different from plot defaults.
#'
#'  * \code{group} The name of the data-series to use to group
#'  plotted data with.
#'
#'  * \code{facet} The name of the data-series to use to cut
#'  the data by when generating multiple plot panels. Also provides
#'  an addition \code{facet.type} shortcut to different \code{ggplot2}
#'  facet options: \code{'wrap'} for \code{facet_wrap} (default),
#'  \code{'grid'} for \code{facet_grid} (or 'grid.row' or grid.col' to
#'  specific by row-then-column or column-then-row grid handling,
#'  respectively).
#'
#'  *  The plots also apply some intuitive reasoning, e.g. the
#'  argument \code{point.col='red'} is equivalent to
#'  \code{plot.type='point'} and \code{col='red'} but only applies
#'  that colour to points if other plot types are requested in
#'  the same call.
#'
#'  Functions like \code{tubeTimePlot} and \code{tubeMap} are
#'  wrappers that provide short-cuts to build commonly used
#'  plots.
#'

## see this about best practice using ggplot2 in a package...
##    (their words not mine..)
## https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html


#' @return \code{tubePlot} is a general purpose plotting functions for
#' diffusion tube data.
#'
#' \code{tubeTimePlot} is a \code{tubePlot} wrapper that adds the tagged
#' sampling date as a second axes if one of \code{x} or \code{y} is
#' supplied.
#'
#' @note Maybe I'm already missing \code{qplot}...


###############################
# documentation notes
###############################

# need to
#######################

# Check through and update following after reset tubePlot updates
# THEN same for tubeMap

# check that key.name (or whatever) works for tubePlot and TubeMap,
#   think it was not always working in Bradford analysis...

# using geom_raster instead of geom_tile to stop aliasing with
#    transparent surfaces BUT very small too.fars may break this ...
# COULD TRY leaving NAs in corners or replace all too.far data with
#    NAs rather than removing them... BUT might mean we cannot
#    reduce the plot range..???


###############################
# added
# tidy what follows when done
###############################

# start these functiions again...
#    merge ggplotTubeShell and tubePlot...
#         see notes

# stat args for geoms maybe come from stat_[...] functions
#    but be careful - there is a lot there...




##


#    reference and link to ggplot2... and/or plotting more generally in R

#    think about default colours
#       The default ggplot2 color for a continuous scale is a blue gradient,
#       specifically a low value of dark blue (#132B43) and a high value of
#       light blue (#56B1F7). This is generated by the default
#       scale_color_gradient() or scale_fill_gradient() functions,
#       which use the seq_gradient_pal() function from the scales package
#       to create the color steps.

# think about
#######################

# decide and document col/colour handling

# decide and document palette and fill.palette handling

# decide and document rotate.x.axes

# decide and document key.position and key.direction



#############################
# code notes - general
#############################

# removed full imports
## #' @import dplyr, etc
## now specifying directly in code, ggplot2::ggplot, etc


# most urgent
############################

# possible issue with point.count when it is same as one of the two axes...
#    see
#      tubeTimePlot(tagTube(dont.share::dt.bradford.2), y="measurement", plot.type = "point.count", size="measurement")
#    and what I think it should look like...
#       tubeTimePlot(tagTube(dont.share::dt.bradford.2), y="measurement", plot.type = "point.count", size=".latitude")
#    related
#       using stat for similar with bar plots
#          see this about stat_... functions
#          https://yjunechoe.github.io/posts/2020-09-26-demystifying-stat-layers-ggplot2/
#       might be an easier option



# think about
##############################

# think about an option to kill the legend...
#    maybe do by default if group or col are factors or characters and too large
#       but they add a kill option

# option rotate axes labels

# control of scale free, free_x, free_y, etc...
#     is currently by ggplotTubeShell that passes scales to the ggplot2::facet_[whatever]
#         this is part of a facet... formals only do.call
#         might fall over is scales is allowed but one of the geoms when used through
#            tubePlot



# think about extending palette to fill?
#    [might now be done... via ggplotTUbeShell?]
#    playing with this...
#    tubePlot(dont.share::dt.bradford.2, plot.type="site", palette=c("white", "green")) + ggplot2::geom_density_2d_filled(breaks=10^(0:10)

# think about an option to pass argument to just one layer
#    can obviously do that in a function...
#        but not from a tubePlot call...

# like something like smooth but not as talkative...

#



####################################
# plotTube
####################################

# common plots wrapper

########################
# third draft ???
########################

# merging tubePlot and ggplotTubeShell to simplify object handling...

# proposing making tubePlot the standard plot
# then tubeTimePlot a variation that by default sets x  to date
# also think about making tubeSitePlot tubeMap without the map...


#test <- function(x, ...){ qs <- quantile(as.numeric(x), c(0.45, 0.5, 0.55), na.rm=T)
#names(qs)<- c("ymin", "y", "ymax")
#qs
#}


#####################
# notes
#####################

# NEED to go through these notes....
#    (some might be done/fixed now...)

# using ggplotTubeShell
#     dte_ggshellTestArgs
#     dte_ggshellAddGeom
#     getTubeX and checkTubeData

# once we have range of required plots agreed
#     we should be able to simplify/automate a lot of this

# playing with

# for quantile ribbon
# test <- function(x, ...){ qs <- quantile(as.numeric(x), c(0.45, 0.5, 0.55), na.rm=T)
# names(qs)<- c("ymin", "y", "ymax")
# qs
# }
# a <- tubePlot(dd[dd$.start_date>"2021-12-31",], ".date", "measurement", plot.type="none")
# a + ggplot2::geom_smooth(ggplot2::aes(group=month, fill=month), stat="summary", fun.data=test, alpha=0.5)
# also see
# geom_smooth(method="gam", formula = y ~ s(x, bs = "cs", k=5))
# can I get k from the data ??? maybe check in each case ???
# a + ggplot2::geom_smooth(ggplot2::aes(group=month, fill=month), alpha=0.5, formula=y~s(x, k=4), method="gam")
# BUT you need to know k and it is different for each group....


# look at following re map handling...
# https://jcoliver.github.io/learn-r/017-open-street-map.html


# nice visualizations....
#    https://www.nature.com/articles/s41467-018-03297-7

# see this about irregular data
#    https://stackoverflow.com/questions/37529116/how-to-plot-a-heat-map-with-irregular-data-in-ordinates-in-ggplot

# also
#    tubePlot(tagTube(dont.share::dt.bradford.2), x=".longitude", y=".latitude", palette=c("white", "green")) + ggplot2::geom_density_2d_filled(breaks=10^(0:10)) +ggplot2::xlim(-2.5,-1) + ggplot2::ylim(53.7, 54)
#       # needs three colours because it is default fill.paletet because no fill in call...
#           # and every if there were, the geom would ignore it because it uses a z term...

# saw this on over.plotting
# https://bookdown.dongzhuoer.com/hadley/ggplot2-book/overplotting

# from https://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette
# gg_color_hue <- function(n) {
#   hues = seq(15, 375, length = n + 1)
#   hcl(h = hues, l = 65, c = 100)[1:n]
#  }
# n <- 5; hcl(h = seq(15, 375, length = n + 1), l = 65, c = 100)[1:n]



# also
#    tubePlot(tagTubeDate(dd), x=".date", y=".latitude", surface.fill=".value")
#       dies because .date has two names...


##############
# issue
###################

## this works
# tubePlot(test, ".date", "..pred", plot.type = "line", group=".location", col="caz.class")
## but this dies
# tubePlot(test, ".date", "..pred", plot.type = "smooth", group=".location", col="caz.class")
# guessing smooth is somehow dropping caz.class from test, maybe through fit model ???
# works if I facet caz.class !!!
## tubePlot(test, ".date", "..pred", plot.type = "smooth", group=".location", col="caz.class", facet="caz.class")
# so guessing it is tracking group and facet but not col, etc....

# this works
# tubePlot(dd, x=".longitude", y=".latitude", size=1, col=".value")
#  but assumes the size needs mapping when it odes not...

################################


# update based on current tubeMap
#    previous tubePlot now unexported tubePlot.old
#
# dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
# dd$.year <- format(tagTubeDate(dd)$.date, "%Y")
# tubePlot(dd, x=".longitude", y=".latitude", palette=c("white", "green"), point.col=".value")

# currently use key.position="none" to remove the key...
#    do we want a key = FALSE option...

# facet or panel as the argument ????

#' @rdname tube.plots
#' @export

tubePlot <-
  function(data, x=NULL, y=NULL, plot.type=NULL, ...){

    #setup
    ####################

    #args
    .xargs <- dte_ggshellTidyArgs(list(...))
    .xargs <- modifyList(list(grid.borders = 0.05,
                              auto.text = TRUE),
                         .xargs)

    #data
    if("ggplot" %in% class(data)){
      plt <- data
      d2 <- data$data
    } else {
      d2 <- data
      plt <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }

    # check/add any requested tags if missing
    d2 <- tagTubeRequired(d2,
              required = c(x, y, unlist(.xargs[sapply(.xargs, is.character)])))
    .xargs.test <- dte_ggshellTestArgs(.xargs, d2)
    .check <- .xargs.test[.xargs.test=="data"]
    .check <- .xargs[names(.xargs) %in% names(.check)]
    d2 <- checkTubeData(d2, x= unlist(.check))
    .xargs.test <- dte_ggshellTestArgs(.xargs, d2)

    #test main plot terms
    if(is.null(x) & is.null(y)){
      stop("[plotTube]> Sorry, need at least one of: x,y \n",
           call.=FALSE)
    }
    if(is.null(y)){
      d2$.index <- 1:nrow(d2)
      y <- ".index"
    } else {
      if(is.null(x)){
        d2$.index <- 1:nrow(d2)
        x <- ".index"
      }
    }
    ##########################################
    # strictly not ggplotTubeShell anymore....
    ##########################################
    d2[, x] <- getTubeX(d2, x, if.err = "stop<<tubePlot>>x")
    d2[, y] <- getTubeX(d2, y, if.err = "stop<<tubePlot>>x")
    # moving next two checks from !is.null(.xargs$...) to %in% names
    # because facet.type without facet trips here
    if("group" %in% names(.xargs)){
      d2 <- checkTubeData(d2, x=.xargs$group, n.x=1,
                            if.err = "stop<<tubePlot>>group")
    }
    if("facet" %in% names(.xargs)){
      d2 <- checkTubeData(d2, x=.xargs$facet, n.x=2,
                            if.err = "stop<<tubePlot>>facet")
    }

    ## (if not already a plot...) build first layer
    ###################
    if(is.null(plt)){
      plt <- ggplot2::ggplot(d2,
                             ggplot2::aes(x=.data[[x]],
                                          y=.data[[y]])
                             )
        #annotation
        if(!"xlab" %in% names(.xargs)){
          .xargs$xlab <- x
        }
        if(!"ylab" %in% names(.xargs)){
          .xargs$ylab <- y
        }
      plt <- plt + ggplot2::theme_bw() +
        ggplot2::theme(strip.background = ggplot2::element_rect(fill="transparent"))
    }

    # plot.type
    # this is so sloppy but it gives me pleasure...
    .check <- c("point", "line", "box", "band", "surface", "smooth", "polygon", "none", "ggsmooth")
    .tt <- c(plot.type, names(.xargs))
    for(i in .check){
      .tt[grepl(paste("^", i, "[.]", sep=""), .tt)] <- i
    }
    plot.type <- unique(.tt[.tt %in% .check])
    if(length(plot.type)==0){
      plot.type <- "point"
    }

    for(i in plot.type){

      # add the plot layers

      #point
      #################################
      # added  overplot option
      #     calculates mean or count of overplot data
      if("point" %in% i){
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "point")
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
        .d2 <- d2
        # overplot in-plot handling
        if("overplot" %in% names(.xargs2)){
          #like a tidier way of doing this
          .by <- c(x, y, .xargs2$facet, .xargs2$group)
          .x <- c()
          if(length(.xargs2)>0){
            for(i in 1:length(.xargs2)){
              #print(.xargs2[[i]]) - value
              #print(names(.xargs2)[i]) - name
              if(.xargs2.test[[i]]=="data"){
                if(!is.numeric(getTubeX(.d2, .xargs2[[i]]))){
                  .by <- c(.by, .xargs2[[i]])
                } else {
                  .x <- c(.x, .xargs2[[i]])
                }
              }
            }
          }
          .by <- unique(.by)
          .x <- unique(.x[!.x %in% .by])
          if(length(.x)<1){
            #add dummy
            .d2$..dummy <- 1
            .x="..dummy"
          }
          if(.xargs2$overplot=="mean"){
            .stat <- function(x) { list(mean=mean(x, na.rm=TRUE)) }
            .d2 <- suppressWarnings(calcTubeStat(.d2, .x, stat=.stat, by =.by))
            .xargs2[.xargs2 %in% .x] <- paste(.xargs2[.xargs2 %in% .x], ".mean", sep="")
            # ignoring dummy means if nothing to mean
          }
          if(.xargs2$overplot=="count"){
            .stat <- function(x) { list(count=length(x[!is.na(x)])) }
            .d2 <- suppressWarnings(calcTubeStat(.d2, .x, stat=.stat, by =.by))
            .xargs2[.xargs2 %in% .x] <- paste(.xargs2[.xargs2 %in% .x], ".count", sep="")
            if("..dummy.count" %in% names(.d2) & !"size" %in% names(.xargs2)){
              .xargs2$size = "..dummy.count"
            }
          }
          # currently ignoring overplot if not understood...
        }
        if(.xargs2$..test=="OK"){
          .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
          ##########################
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPoint)]
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_point,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
        }
      }

###############################################
# polygon twice
# check nothing different here before fully removing
#############################################

#      #polygon
#      if("polygon" %in% i){
#        ##########################
#        #testing this tidy
#        #    Holding code because it is very sensitive to ordering
#        #.xargs2 <- .xargs[grepl("^polygon[.]", names(.xargs))]
#        #names(.xargs2) <- gsub("polygon[.]", "", names(.xargs2))
#        #names(.xargs2)[names(.xargs2) %in% c("col", "color")] <- "colour"
#        #.xargs2 <- .xargs2[!duplicated(names(.xargs2), fromLast=TRUE)]
#        #.xargs2 <- modifyList(.xargs, .xargs2)
#        .xargs2 <- dte_ggshellTidyArgs(.xargs, "polygon")
#        if(.xargs2$..test=="OK"){
#          .xargs2 <- modifyList(.xargs2, list(x="X", y="Y"))
#          ##########################
#          # to think about...
#          #    this currently needs polygon to be a sf polygon...
#          #        BUT polygon could be a different object type ...
#          #        OR polygon could be true... then you would use the data as polygon source
#          #            can't colour a polygon by palette at moment
#          .xargs2$polygon <- as.data.frame(sf::st_coordinates(.xargs2$polygon))
#          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPolygon)]
#          plt <- dte_ggshellAddGeom(.xargs2, .xargs2$polygon, plt,
#                                    ggplot2::geom_polygon,
#                                    defaults = list(na.rm=TRUE, colour="blue",
#                                                    fill="blue", alpha=0.25),
#                                    drops = drops)
#        }
#      }

      #polygon
      if("polygon" %in% i){
        ##########################
        #testing this tidy
        #    Holding code because it is very sensitive to ordering
        #.xargs2 <- .xargs[grepl("^polygon[.]", names(.xargs))]
        #names(.xargs2) <- gsub("polygon[.]", "", names(.xargs2))
        #names(.xargs2)[names(.xargs2) %in% c("col", "color")] <- "colour"
        #.xargs2 <- .xargs2[!duplicated(names(.xargs2), fromLast=TRUE)]
        #.xargs2 <- modifyList(.xargs, .xargs2)
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "polygon")
        if(.xargs2$..test=="OK"){
          .xargs2 <- modifyList(.xargs2, list(x="X", y="Y"))
          ##########################
          # to think about...
          #    this currently needs polygon to be a sf polygon...
          #        BUT polygon could be a different object type ...
          #        OR polygon could be true... then you would use the data as polygon source
          #            can't colour a polygon by palette at moment
          .xargs2$polygon <- as.data.frame(sf::st_coordinates(.xargs2$polygon))
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPolygon)]
          plt <- dte_ggshellAddGeom(.xargs2, .xargs2$polygon, plt,
                                    ggplot2::geom_polygon,
                                    defaults = list(na.rm=TRUE, colour="blue",
                                                    fill="blue", alpha=0.25),
                                    drops = drops)
        }
      }


      #bad.smooth
      if("smooth" %in% i){
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "smooth")
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
        # needs groups
        # if fill or col declared...
        #     tracking in order fill, then colour
        if(!"group" %in% names(.xargs2)){
          .test <- c(.xargs2$fill, .xargs2$colour)
          .test <- unlist(.xargs[names(.xargs.test[.xargs.test=="data"])])
          if(length(.test)>0){
            .xargs2$group <- .test[1]
          }
        }
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
        .fit.args <- modifyList(list(data=d2, tube=y,
                                     inputs=x, by=c(.xargs2$group, .xargs2$facet),
                                     simplify=FALSE,
                                     model = function(data, tube, inputs, new.data = NULL, ...){

                                       data$..y. <- as.numeric(data[[tube]])
                                       data$..x. <- as.numeric(data[[inputs[1]]]) # only handling first
                                       ..k <- unique(data$..x.)
                                       ..k <- length(..k[!is.na(..k)])
                                       if(..k > 10){
                                         ..k = - 1
                                       }
                                       if(is.null(new.data)){
                                         new.data <- data.frame(seq(min(data[[inputs[1]]], na.rm=TRUE),
                                                                    max(data[[inputs[1]]], na.rm=TRUE),
                                                                    length.out=100))
                                         names(new.data) <- inputs[1]
                                         new.data$..x. <- as.numeric(new.data[[inputs[1]]])
                                       }
                                       row.names(data) <- 1:nrow(data)
                                       ######################
                                       # think about
                                       # formula = 'y ~ s(x, bs = "cs")'
                                       ###################
                                       mod <- mgcv::gam(..y. ~ s(..x., k=..k), data=data)
                                       .tmp <- mgcv::predict.gam(mod, newdata=new.data, se.fit=TRUE)
                                       new.data$..pred <- NA
                                       new.data$..pred[as.numeric(names(.tmp$fit))] <- as.vector(.tmp$fit)
                                       new.data$..s.err <- NA
                                       new.data$..s.err[as.numeric(names(.tmp$se.fit))] <- as.vector(.tmp$se.fit)
                                       new.data <- new.data[names(new.data) != "..x."]
                                       new.data
                                     }
        ),
        #################################
        # could generalise next bit ???
        #    should loose force.positive
        #        it kills models if x or y not numeric...
        #################################
        .xargs2[names(.xargs2) %in% c("too.far", "model",
                                      "simplify",
                                      "force.positive",
                                      "grid.resolution")])
        .d2 <- do.call(fitTubeModel, .fit.args)
        #.xargs2[[y]] <- paste(y, ".pred", sep="")
        if(.xargs2$..test=="OK"){
          #########################
          # tidy this....
          #########################
          y <- paste(y, ".pred", sep="")
          .d2$..ymax. <- .d2[[y]] + (.d2[["..s.err"]] * 1.96)
          .d2$..ymin. <- .d2[[y]] - (.d2[["..s.err"]] * 1.96)
          .xargs2 <- modifyList(list(x=x, y=y, ymax="..ymax.", ymin="..ymin."), .xargs2)
          #.xargs2$fill <- .xargs2[[.test[1]]]
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomSmooth)]
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_smooth,
                                    defaults = list(na.rm=TRUE, se=TRUE, fill=grey(0.5), stat="identity"),
                                    drops = drops[!c(drops) %in% c("ymax", "ymin", "se")])
#   now using deom_smooth
#          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRibbon)]
#          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
#                                    ggplot2::geom_ribbon,
#                                    defaults = list(na.rm=TRUE, alpha=0.3),
#                                    drops = c(drops, "col", "color", "colour"))
#          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomLine)]
#          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
#                                    ggplot2::geom_line,
#                                    defaults = list(na.rm=TRUE),
#                                    drops = c(drops, "fill"))
        }
      }

      if("ggsmooth" %in% i){
        ##########################
        # testing this tidy
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "ggsmooth")
        if(.xargs2$..test=="OK"){
          .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
          ##########################
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomSmooth)]
          drops <- drops[drops!="k"]
          #########################
          # null to force the gam...
          #  trying to set k to set the knots...
          # not working!!!!
          #########################
          plt <- dte_ggshellAddGeom(.xargs2, d2, plt,
                                    ggplot2::geom_smooth,
                                    defaults = list(na.rm=TRUE, method=NULL),
                                    drops = drops)
        }
      }


      #surface
      if("surface" %in% i){
        #NB: hijacking na.value if using surface
        if(!"na.value" %in% names(.xargs)){
          .xargs$na.value <- NA
        }
        #just contour arg should trigger contour ??
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "surface")
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
        .test <- names(.xargs2.test[.xargs2.test=="data"])
        .test <- .test[.test %in% c("fill", "z", "colour", "contour")]
        if(length(.test)>0){
          .fit.args <- modifyList(list(data=d2, tube=.xargs2[[.test[1]]],
                                       inputs=c(x,y), by=c(.xargs$group, .xargs$facet),
                                       simplify=TRUE, new.data="input.ranges"),
                                  #################################
                                  # could generalise next bit ???
                                  #################################
                                  .xargs2[names(.xargs2) %in% c("too.far", "model",
                                                                "simplify",
                                                                "force.positive",
                                                                "grid.resolution",
                                                                "grid.borders")])
          .d2 <- do.call(fitTubeModel, .fit.args)
          .xargs2[[.test[1]]] <- paste(.xargs2[[.test[1]]], ".pred", sep="")
          if(.xargs2$..test=="OK"){
            .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
            ##########################
            # if fill in there
            if("fill" %in% names(.xargs2)){
              .xargs2$fill <- .xargs2[[.test[1]]]
              drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRaster)]
              drops <- c(drops, "col", "color", "colour")
              plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                        ggplot2::geom_raster,
                                        defaults = list(na.rm=TRUE),
                                        drops = drops)
            }
            if("contour" %in% names(.xargs2)){
              ###################
              # fix for contour.[whatever]
              # maybe contour should be black if no fill and no col..?
              .xargs2$z <- .xargs2[[.test[1]]]
              drops <-  names(.xargs2)[!names(.xargs2) %in%
                                         c(dte_GeomArgs(ggplot2::GeomContour), "z")]
              drops <- c(drops, "fill", "alpha")
              plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                        ggplot2::geom_contour,
                                        defaults = list(na.rm=TRUE,
                                                        colour="white"),
                                        drops = drops)
              plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                        metR::geom_text_contour,
                                        defaults = list(na.rm=TRUE,
                                                        colour="white"),
                                        drops = drops)
            }
          }
        }
      }

      # line
      #############################################
      # can't decide between line and path
      # this get high jacked to make precision  works
      if("line" %in% i){
          .xargs2 <- dte_ggshellTidyArgs(.xargs, "line")
          .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
          .d2 <- d2[order(d2[[x]]),]
          # has a gap option
          # like options for  geom_line/geom_path switch...
          # also like y as well as x lines...
          # like more control of the line
          #     maybe gap.linetype dotted, dashed, solid, none ???
          # not quite the same but see:
          #    https://stackoverflow.com/questions/56763116/plotting-missing-values-in-ggplot2-with-a-separate-line-type
          if(.xargs2$..test=="OK"){
            .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
            #####################
            # tidy this when time
            #  simplify the two ifs/drop ..na.pad. .... ???
            #####################
            ..na.pad. <- if("gap" %in% names(.xargs2) & "group" %in% names(.xargs2)){
              .xargs$gap
            } else {
              FALSE
            }
            ##########################
            if(..na.pad.){
              .old.lt <- .xargs2$linetype
              .xargs2$linetype <- "dotted"
              drops <- names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPath)]
              plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                        ggplot2::geom_path,
                                        defaults = list(na.rm=TRUE),
                                        drops = drops)
              .xargs2$linetype <- .old.lt
              ..test. <- names(.xargs2.test[.xargs2.test=="data"])
              if(length(..test.)>0){
                ..test. <- unique(unlist(.xargs2[..test.]))
              }
              ..test. <- unique(c(x, y, ..test.))
              .d3 <- .d2[..test.]
              ######################################
              #think about sort()
              #also rethink this section
              #   it could be a lot cleaner/quicker
              #   also I think wrong combination of terms will kill it...
              #   also like to control linetype, linewidth, etc
              #        for the missing data section (dotted, dashed, none, etc)
              #####################################
              ..tmp. <- lapply(names(.d3)[names(.d3)!=y], function(x){sort(unique(.d3[[x]]))})
              names(..tmp.) <- names(.d3)[names(.d3)!=y]
              ..tmp. <- do.call(expand.grid, ..tmp.)
              .d3 <- merge(.d3, ..tmp., all=TRUE)
              ..tmp. <- data.table::as.data.table(.d3)
              #print(names(..tmp.))
              #print(y)
              #print(..test.[!..test. %in% c(x,y)])
              ..tmp. <- calcTubeStat(..tmp., y, by=..test.[!..test. %in% c(x,y)])
              ..tmp. <- ..tmp.[!is.na(..tmp.[[paste(y, ".mean", sep="")]]),]
              .d3 <- merge(..tmp., .d3, all.x=TRUE)
              .d3 <- .d3[order(.d3[[x]]),]
              drops <- names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPath)]
              plt <- dte_ggshellAddGeom(.xargs2, .d3, plt,
                                        ggplot2::geom_path,
                                        defaults = list(na.rm=TRUE),
                                        drops = drops)
            } else {
              drops <- names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPath)]
              plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                        ggplot2::geom_path,
                                        defaults = list(na.rm=TRUE),
                                        drops = drops)
            }
          }
      }

      # box
      #################################
      #old box
     #  temp <- TRUE
     #  .xargs2 <- .xargs # might want the group going to all
     #  data2 <- data
     #  if(!".default" %in% c(x,y)){
     #    if(!"group" %in% names(.xargs2)){
     #      ###########################
     #      # note
     #      ###########################
     #      # this'll die if both are numeric...
     #      .test <- unique(unlist(.xargs2[names(.xargs.test[.xargs.test=="data"])]))
     #      if(is.numeric(getTubeX(data, x))){
     #        data2$..group <- paste(getTubeX(data2, y), data2[[.test]])
     #      } else {
     #        data2$..group <- paste(getTubeX(data2, x), data2[[.test]])
     #      }
     #      .xargs2$group <- "..group"
     #    }
     #  }
     #  drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomBoxplot)]
     #  out <- dte_ggshellAddGeom(.xargs2, data2, out,
     #                            ggplot2::geom_boxplot,
     #                            defaults = list(na.rm=TRUE, fill="grey"),
     #                            drops = drops)
     #}
      if("box" %in% i){
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "box")
        .d2 <- d2
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, .d2)
        #if(!"group" %in% names(.xargs2)){
          # needs more work, might not be x...
          # also need a more complex group if
          # col/fill in there and not dividable...
          ## dd <- tagTubeDate(dd)
          ## dd$special <- paste(dd$.date, dd$sic)
          ## tubeTimePlot(dd, y=".value", plot.type="box", fill="sic", group="special")
        #  .xargs2$group <- x
        #}

        if(!"group" %in% names(.xargs2)){
            ###########################
            # note
            ############################
            # this'll die if both are numeric...

          ..test. <- names(.xargs2.test[.xargs2.test=="data"])
          if(length(..test.)>0){
            ..test. <- unique(unlist(.xargs2[..test.]))
            ..test. <- ..test.[!..test. %in% c(x,y)]
          }
          if(is.numeric(getTubeX(.d2, x))){
            .d2$..group <- apply(.d2[c(y, ..test.)], 1, function(x)
              paste(unlist(paste(x)), collapse = "&"))
            .xargs2$group <- "..group"
          } else {
            .d2$..group <- apply(.d2[c(x, ..test.)], 1, function(x)
               paste(unlist(paste(x)), collapse = "&"))
            .xargs2$group <- "..group"
          }
        }
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, .d2)
        if(.xargs2$..test=="OK"){
          .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
          ##########################
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomBoxplot)]
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_boxplot,
                                    defaults = list(na.rm=TRUE, fill="grey"),
                                    drops = drops)
        }
      }

      #band
      if("band" %in% i){
        .xargs2 <- dte_ggshellTidyArgs(.xargs, "band")
        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
        .d2 <- d2
        # note: I need to mess with this...
        #set to "x.stat.ribbon" or "y.stat.ribbon" if not set
        .b.dir <- if("cheat" %in% .xargs2){
          .xargs2$cheat
        } else {
          "by-x"
        }
        ##############################
        # building .x and .by - hooping to remove this
        .by <- c(x, y, .xargs2$facet, .xargs2$group)
        .x <- c()
        if(length(.xargs2)>0){
          for(j in 1:length(.xargs2)){
            #print(.xargs2[[j]]) - value
            #print(names(.xargs2)[j]) - name
            if(.xargs2.test[[j]]=="data"){
              if(!is.numeric(getTubeX(.d2, .xargs2[[j]]))){
                .by <- c(.by, .xargs2[[j]])
              } else {
                .x <- c(.x, .xargs2[[j]])
              }
            }
          }
        }
        .by <- unique(.by)
        .x <- unique(.x[!.x %in% .by])
        if(length(.x)<1){
          #add dummy
          .d2$..dummy <- 1
          .x="..dummy"
        }
        ##########################
        # using probs because it aligns with the quantile error
        ##########################
        .q <- if(is.null(.xargs$band.probs)){
          c(0, 0.5, 1)
        } else {
          .xargs$band.probs
        }

        if(.xargs2$..test=="OK"){
          if(.b.dir=="by-x"){
          ##########################
          # anything here needs to be duplicated above...
          # (when sorted we should be able to rationalise a lot of these)
          ##########################
          .stat <- function(x) { list(y.mid=stats::quantile(x, probs=.q[2], na.rm=TRUE, names=FALSE),
                                      y.low=stats::quantile(x, probs=.q[1], na.rm=TRUE, names=FALSE),
                                      y.hi=stats::quantile(x, probs=.q[3], na.rm=TRUE, names=FALSE)) }
          .d2 <- suppressWarnings(calcTubeStat(.d2, y, stat=.stat, by=
                                                unique(c(.x, .by)[!c(.x,.by) %in% y])))
          .d2 <- .d2[order(getTubeX(.d2, x)),]
          if("colour" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs2.test["colour"]=="data"){
              .xargs2$group <- .xargs$colour
            }
          }
          if("fill" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs2.test["fill"]=="data"){
              .xargs2$group <- .xargs$fill
            }
          }
          .xargs2$y <- paste(y, ".y.mid", sep="")
          .xargs2$ymin <- paste(y, ".y.low", sep="")
          .xargs2$ymax <- paste(y, ".y.hi", sep="")
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRibbon)]
          drops <- c(drops, "colour")
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_ribbon,
                                    defaults = list(na.rm=TRUE,
                                                    fill="grey", alpha=0.5),
                                    drops = drops)
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomLine)]
          drops <- c(drops, "alpha")
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_line,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)

        } else {
            .stat <- function(x) { list(x.mid=stats::quantile(x, probs=.q[2], na.rm=TRUE, names=FALSE),
                                        x.low=stats::quantile(x, probs=.q[1], na.rm=TRUE, names=FALSE),
                                        x.hi=stats::quantile(x, probs=.q[3], na.rm=TRUE, names=FALSE)) }
            .d2 <- suppressWarnings(calcTubeStat(.d2, x, stat=.stat, by=
                                                unique(c(.x,.by)[!c(.x,.by) %in% x])))
            .d2 <- .d2[order(getTubeX(.d2, y)),]
            if("colour" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
              # if we have a col we need a group
            # BUT only copy if col is in data copy col
            if(.xargs2.test["colour"]=="data"){
              .xargs2$group <- .xargs$colour
            }
          }
          if("fill" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs2.test["fill"]=="data"){
              .xargs2$group <- .xargs$fill
            }
          }
          .xargs2$x <- paste(x, ".x.mid", sep="")
          .xargs2$xmin <- paste(x, ".x.low", sep="")
          .xargs2$xmax <- paste(x, ".x.hi", sep="")
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRibbon)]
          drops <- c(drops, "colour")
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_ribbon,
                                    defaults = list(na.rm=TRUE,
                                                    fill="grey", alpha=0.5),
                                    drops = drops)
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomLine)]
          drops <- c(drops, "alpha")
          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                    ggplot2::geom_path,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
          }
        }
      }




      #next plot.type here...
      # current template
      # add plot.type to check...
      #################################
#      if("point" %in% i){
#        .xargs2 <- dte_ggshellTidyArgs(.xargs, "point")
#        .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
#        .d2 <- d2
#        if(.xargs2$..test=="OK"){
#          .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
#          ##########################
#          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPoint)]
#          plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
#                                    ggplot2::geom_point,
#                                    defaults = list(na.rm=TRUE),
#                                    drops = drops)
#        }
#      }




    }


    #any facetting?
    if("facet" %in% names(.xargs)){
      #don't need facet.type if no facet...
      if(!"facet.type" %in% names(.xargs)){
        .xargs$facet.type <- "wrap"
      } else {
        check <- c("wrap", "grid", "grid.col", "grid.row")
        if(!.xargs$facet.type %in% check){
          warning("bad facet.type resetting to wrap")
          .xargs$facet.type <- "wrap"
        }
      }
      ## facet.type choices limited earlier
      #####################
      #tesing
      # passing just ggplot2::facet... args forward
      # names(formals(ggplot2::facet_grid)), etc....
      # if you give it facet, rows or cols
      #     these will override as well
      # does the job but code is messy...
      #####################
      ..xargs <- if(.xargs$facet.type=="wrap"){
        .xargs[names(.xargs) %in% names(formals(ggplot2::facet_wrap))]
      } else {
        #most be a facet_grid
        .xargs[names(.xargs) %in% names(formals(ggplot2::facet_grid))]
      }
      if(length(.xargs$facet)== 1){
        if(.xargs$facet.type=="wrap"){
          ..xargs <- modifyList(list(facets=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_wrap, ..xargs)
          #plt <- plt + ggplot2::facet_wrap(facets=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
        if(.xargs$facet.type %in% c("grid", "grid.row")){
          ..xargs <- modifyList(list(rows=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_grid, ..xargs)
          #plt <- plt + ggplot2::facet_grid(rows=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
        if(.xargs$facet.type %in% c("grid.col")){
          ..xargs <- modifyList(list(cols=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_grid, ..xargs)
          #plt <- plt + ggplot2::facet_grid(cols=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
      } else{
        if(.xargs$facet.type %in% c("wrap")){
          ..xargs <- modifyList(list(facets=c(ggplot2::vars(.data[[.xargs$facet[1]]]),
                                              ggplot2::vars(.data[[.xargs$facet[2]]]))),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_wrap, ..xargs)
          #plt <- plt + ggplot2::facet_wrap(facets=c(ggplot2::vars(.data[[.xargs$facet[1]]]),
          #                                 ggplot2::vars(.data[[.xargs$facet[2]]])))
        }
        if(.xargs$facet.type %in% c("grid", "grid.row")){
          plt <- plt + ggplot2::facet_grid(rows=ggplot2::vars(.data[[.xargs$facet[1]]]),
                                           cols=ggplot2::vars(.data[[.xargs$facet[2]]]))
        }
        if(.xargs$facet.type %in% c("grid.col")){
          plt <- plt + ggplot2::facet_grid(cols=ggplot2::vars(.data[[.xargs$facet[1]]]),
                                           rows=ggplot2::vars(.data[[.xargs$facet[2]]]))
        }
      }
    }

    #palette
    #palette
    ############################
    # note
    ############################
    #   testing a colouring option
    #      alpha control limited at moment
    #      NB:need to make any changes for palette/colour and fill.palette/fill
    #   currently setting NA.value to NA in scale_fill_gradientn for surface tubePlot
    #      could set this NA.value for surface only..?
    ############################
    #test for map-able fills
    .tt <- names(.xargs.test[.xargs.test=="data"])
    .tt <- c(.tt[.tt %in% c("col", "color", "colour")],
             grep("[.]col|[.]color|[.]colour", .tt, value=TRUE))
    .pp <- c()
    #na colour handling (hijacking this for surface fit/raster)
    .na.value <- if("na.value" %in% names(.xargs)){
      .xargs$na.value
    } else {
      "grey50"
    }
    if(length(.tt)>0) {
      .pp <- getTubeX(d2, .xargs[[.tt[1]]])
    }
    if(!"palette" %in% names(.xargs) & length(.pp)>0){
      .xargs$palette <- if(is.numeric(.pp)){
        c("#132B43", "#56B1F7")
      } else {
        hcl(h = seq(15, 375, length = length(unique(.pp)) + 1),
            l = 65, c = 100)[1:length(unique(.pp))]
#        if(length(unique(.pp)) > length(.xargs$fill.palette)){
#          colorRampPalette(c("#F8766D", "#A3A500", "#00BF7D",
#                             "#00B0F6", "#E76BF3"))(length(unique(.pp)))
#        } else{
#          c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3")
#        }
      }
    }

    if("palette" %in% names(.xargs)){
      # colours might not be being mapped
      .value <- if("alpha" %in% names(.xargs)){
        ggplot2::alpha(.xargs$palette, .xargs$alpha)
      } else {
        .xargs$palette
      }
      if(length(.pp)==0){
        ###########################
        # testing removing - same in fill.palette
        ##plt$mapping$colour <- "default"
        plt <- plt + ggplot2::scale_color_manual(values=.value,
                                                 na.value=.na.value,
                                                 guide="none")
      } else {
        #.pp <- data[[rlang::as_label(plt$mapping$colour)]]
        #.pp <- plt$mapping$colour
        if(is.numeric(.pp)){
          plt <- plt + ggplot2::scale_color_gradientn(colours=.value,
                                                      na.value=.na.value)
        } else {
          if(length(unique(.pp)) > length(.value)){
            .value <- colorRampPalette(.value)(length(unique(.pp)))
          }
          plt <- plt + ggplot2::scale_color_manual(values=.value,
                                                   na.value=.na.value)
        }
      }
    }

    #fill.palette
    ############################
    # note
    ############################
    #   testing a colouring option
    #      alpha control limited at moment
    #      NB:need to make any changes for palette/colour and fill.palette/fill
    #   currently setting NA.value to NA in scale_fill_gradientn for surface tubePlot
    ############################

    #test for map-able fills
    .tt <- names(.xargs.test[.xargs.test=="data"])
    .tt <- c(.tt[.tt=="fill"], grep("[.]fill", .tt, value=TRUE))
    .pp <- c()
    if(length(.tt)>0) {
      .pp <- getTubeX(d2, .xargs[[.tt[1]]])
    }

    if("palette" %in% names(.xargs) & ! "fill.palette" %in% names(.xargs)){
      .xargs$fill.palette <- .xargs$palette
    }
    if(!"fill.palette" %in% names(.xargs) & length(.pp)>0){
      .xargs$fill.palette <- if(is.numeric(.pp)){
        c("#132B43", "#56B1F7")
      } else {
        hcl(h = seq(15, 375, length = length(unique(.pp)) + 1),
            l = 65, c = 100)[1:length(unique(.pp))]
        #if(length(unique(.pp)) > length(.xargs$fill.palette)){
        #  colorRampPalette(c("#F8766D", "#A3A500", "#00BF7D",
        #                     "#00B0F6", "#E76BF3"))(length(unique(.pp)))
        #} else{
        #  c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3")
        #}
      }
    }

    if("fill.palette" %in% names(.xargs)){
      .value <- if("alpha" %in% names(.xargs)){
        # NB: alpha just updates, not a multiple,
        #     alpha(alpha(cols, 0.5), 0.5) == alpha(cols, 0.5)
        ggplot2::alpha(.xargs$fill.palette, .xargs$alpha)
      } else {
        .xargs$fill.palette
      }

      # like colours might not be being mapped
      # could also be a [whatever].fill
      if(length(.pp)==0){
        #############################################
        # testing removing - same in fill.palette
        plt$mapping$fill <- "default"
        plt <- plt + ggplot2::scale_fill_manual(values=.value,
                                                na.value=.na.value,
                                                guide="none")

      } else {
        #.pp <- data[[rlang::as_label(plt$mapping$colour)]]
        #.pp <- plt$mapping$colour
        .pp <- getTubeX(d2, .xargs[[.tt[1]]])
        if(is.numeric(.pp)){
          plt <- plt + ggplot2::scale_fill_gradientn(colours=.value,
                                                     na.value=.na.value)
        } else {
          if(length(unique(.pp)) > length(.value)){
            .value <- colorRampPalette(.value)(length(unique(.pp)))
          }
          plt <- plt + ggplot2::scale_fill_manual(values=.value,
                                                  na.value=.na.value)
        }
      }
    }

    #########################
    #force legend together if multiple are mapped
    #messy.... should only be if mapped to the same arg...
    #    think about setting combination during geom calls
    ########################
    if(length(names(.xargs)[names(.xargs) %in% c("colour", "size", "fill")]) >1){
      if("colour" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(colour=ggplot2::guide_legend())
      }
      if("size" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(size=ggplot2::guide_legend())
      }
      if("fill" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(fill=ggplot2::guide_legend())
      }
    }

    #annotation
    ###########################
    if("xlab" %in% names(.xargs)){
      # move from xlab and ylab to labs ???
      plt <- plt + ggplot2::xlab(dte_quickText(.xargs$xlab, .xargs$auto.text))
    }
    if("ylab" %in% names(.xargs)){
      # move from xlab and ylab to labs ???
      plt <- plt + ggplot2::ylab(dte_quickText(.xargs$ylab, .xargs$auto.text))
    }
    if(.xargs$auto.text){
      # will need to add other labels
      plt <- plt +  ggplot2::theme(axis.title.x = ggtext::element_markdown(),
                                   axis.title.y = ggtext::element_markdown())
    }

    if("rotate.x.axes" %in% names(.xargs)){
      if(is.logical(.xargs$rotate.x.axes) && .xargs$rotate.x.axes){
        .xargs$rotate.x.axes <- 90
      }
      if(is.numeric(.xargs$rotate.x.axes)){
        # to do
        # tidy vjust and hjust if not 90
        plt <- plt + ggplot2::theme(axis.text.x = ggtext::element_markdown(angle=.xargs$rotate.x.axes[1],
                                                                           vjust=0.5, hjust=1))
      }
    }

    if(any(c("key.position", "key.direction") %in% names(.xargs))){
      # to do
      # guessing this might want tidying???
      plt <- plt + ggplot2::theme(legend.position = .xargs$key.position,
                                  legend.direction = .xargs$key.direction)
    }
    if("key.name" %in% names(.xargs)){
      ..tmp. <- ggplot2::get_labs(plt)
      # next needs thinking about because it'll only works by removing
      #    KNOWN non-aes labels and will be others...
      #    from names(formals(ggplot2::labs))
      ..tmp. <- ..tmp.[names(..tmp.) %in% names(.xargs)[!names(.xargs) %in%
                         c("x.sec", "x", "y", "y.sec", "title", "alt",
                           "subtitle", "caption", "tag", "dictionary",
                           "alt", "alt_insight")]]
      #change object content NOT object...
      ..tmp.[] <- rep(.xargs$key.name, length=length(..tmp.))
      if(length(..tmp.)>0){
        plt <- plt + do.call(ggplot2::labs, ..tmp.)
      }
    }

    return(plt)

  }









####################################
# tubeTimePlot
####################################

# tubePlot wrapper that adds .date was other axes if one already set...

# to time about
###################################

# default x/ylab if x/y set ?

#' @rdname tube.plots
#' @export


tubeTimePlot <-
  function(data, x=NULL, y=NULL,
           ...){

    #setup
    .xargs <- list(...)
    #data
    if("ggplot" %in% class(data)){
      data$data <- data$data
    } else {
      data <- data
    }
    #if("new.data" %in% names(.xargs)) {
    #  data<-.xargs$new.data
    #  # have to assume they have this sorted
    #}
    ###################
    # time plot currently needs one of x or y set
    # might be a few cases where this could/should be allowed?
    #    tubeTimePlot(dt.york, plot.type = "bar", col="month")
    #    others...
    if(is.null(x) & !is.null(y)){
      x <- ".date"
    }
    if(is.null(y) & !is.null(x)){
      y <- ".date"
    }
    tubePlot(data = data, x = x, y = y,
             ...)

}

