############################################
#' @title Diffusion Tube maps
############################################

#' @name tube.maps
#' @aliases tube.maps tubeMap leafletTubeMap
#' @description \code{DTEval} currently provides static \code{ggplot2} and
#' dynamic (html) \code{leaflet} diffusion tube maps.
#' @param data Data source to be used to build a plot. This is typically a
#' data.frame or similar, but can also be a previous plot generated by the
#' same function.
#' @param x,y The names of the data-series to plot on the
#' X and Y axes, respectively, and assumed to be sampling point longitude and
#' latitude.
#' @param plot.type The type of plot(s) to produce, e.g.:
#' \code{'point'} (default) for a scatter plot, \code{'surface'} to
#' fit a surface, etc...
#' @param ... Additional arguments. \code{tubeMap} uses \code{data}, \code{x},
#' \code{y} and optional argument \code{facet} to build map layers then passes
#' arguments on to \code{tubePlot} to generate plot layers.


# #' * \code{xlab}, \code{ylab} The X and Y axes labels to use if
# #' different from plot defaults.
# #'
# #'  * \code{group} The name of the data-series to use to group
# #'  plotted data with. By default, \code{ggplotTubeShell} assumes
# #'  supplied groups are factors if less than 20 unique cases.
# #'
# #'  * \code{facet} The name of the data-series to use to cut
# #'  the data by when generating multiple plot panels. Also provides
# #'  an addition \code{facet.type} shortcut to different \code{ggplot2}
# #'  facet options: \code{'wrap'} for \code{facet_wrap} (default),
# #'  \code{'grid'} for \code{facet_grid} (or 'grid.row' or grid.col' to
# #'  specific by row-then-column or column-then-row grid handling,
# #'  respectively).

#' @note
#' These functions are in development, so may change.


#' @return \code{tubeMap} generates static maps using \code{ggplot2}
#' and \code{OpenStreetMap}. \code{leafletTubeMap} generates interactive
#' (HTML) maps using \code{leaflet}.


#############################
# notes
#############################

# removed full imports
#    now always specifying directly in code, ggplot2::ggplot, etc
#    bit painful but some guessing some loading orders are generating conflicts

# don't use is.null(list(...)$facet), etc to test for facet
#    because it partial matches to longer facet... names if facet not there!!!
# same for groups, etc...



###########################
# tubeMap
###########################

# draw maps of tube locations

# notes
############################

# separated leaflet and ggplot2 versions
#   so this is just ggplot these days...

# current test
#    dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
#    tubeMap(dd, facet=".year")

#' @rdname tube.maps
#' @export

tubeMap <-
  function(data, x=NULL, y=NULL, ...){

    #setup
    ####################
    .xargs <- list(...)
    if("ggplot" %in% class(data)){
      previous <- data
      d2 <- data$data
    } else {
      d2 <- data
      previous <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }

    #what to do about col/colour...?
    #   currently using this cludge in tubePlot
    #      and assuming colour hereafter...
    names(.xargs)[names(.xargs) %in% c("col", "color")] <- "colour"
    .xargs <- .xargs[!duplicated(names(.xargs), fromLast=TRUE)]
    if(is.null(x)){
      x <- ".longitude"
    }
    if(is.null(y)){
      y <- ".latitude"
    }

    d2 <- tagTubeRequired(d2, required=c(x, y, .xargs$facet))

    .x <- getTubeX(d2, x, if.err="stop<<tubeMap>>x")
    .y <- getTubeX(d2, y, if.err="stop<<tubeMap>>y")

    if(!"grid.borders" %in% names(.xargs)){
      .xargs$grid.borders <- 0.05
    }

    ##build map layer
    ###################
    if(is.null(previous)){
      #map ranges
      rng.lat <- range(.y, na.rm=TRUE)
      rng.lon <- range(.x, na.rm=TRUE)
      #adding border
      exp <- function(rng, n=0.1){
        temp <- (rng[2]-rng[1])*n
        c(rng[1]-temp, rng[2]+temp)
      }
      rng.lon <- exp(rng.lon, .xargs$grid.borders)
      rng.lat <- exp(rng.lat, .xargs$grid.borders)
      dc <- OpenStreetMap::openmap(c(rng.lat[2], rng.lon[1]),
                                   c(rng.lat[1],rng.lon[2]),
                                   zoom = NULL,
                                   type =  "esri",
                                   mergeTiles = TRUE)

      dc <- suppressMessages(suppressWarnings(
        OpenStreetMap::openproj(dc,
                                projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
      ))
      p1 <- dc$bbox$p1
      p2 <- dc$bbox$p2
      .bb <- data.frame(x = c(p1[1], p2[1]),
                        y = c(p1[2], p2[2]))
      names(.bb) <- c(x,y)
      if("facet" %in% names(.xargs)){
        .bb <- data.frame(.bb, facet=rep(unique(d2[[.xargs$facet]]), each=2))
        names(.bb)[3] <- .xargs$facet
      }
      #####################################
      # would like to simplify this bit...
      ######################################

      .all <- modifyList(list(data=d2, x=x, y=y), .xargs)
      # do I need to send all at this stage ???
      # would just data+x+y work to build the basic ggplot objects ???
      # test when this project has some quiet time ...
      plt <- suppressMessages(suppressWarnings(
        do.call(tubePlot, .all)
      ))
      .ggshell <- c("facet.type", "xlab", "ylab",
                    "auto.text", "palette", "fill.palette", "map.args",
                    "key.position", "key.direction", "rotate.x.axes")
      .xargs <- .xargs[!names(.xargs) %in% .ggshell]
      .xargs <- modifyList(list(x=x, y=y),
                           .xargs)

      for(tile in dc$tiles){
        p1 <- tile$bbox$p1
        p2 <- tile$bbox$p2
        rast <- matrix(tile$colorData, nrow = tile$xres, byrow = TRUE)
        plt <- plt + ggplot2::annotation_raster(rast, -Inf, Inf, -Inf, Inf)
      }

      plt <- plt + ggplot2::expand_limits(x = c(p1[1], p2[1]),
                                          y = c(p2[2], p1[2])) +
        ggplot2::scale_x_continuous(expand = c(0, 0)) +
        ggplot2::scale_y_continuous(expand = c(0, 0))

      ##########################
      # need to re-instate these
      #    (if we can stop them
      #     erroring out...)
      ##########################

      #dies of facetting...
      #plt <- plt + ggplot2::geom_label(x=rng.lon[2], y=rng.lat[1],
      #                                 label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                                 #fill="white", border.colour="white",
      #                                 #size=1.8,
      #                                  hjust=1, vjust=0.20, size=1.8, size.unit = "pc")

      #                      ggplot2::aes(x=x, y=y),
      #                      label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                      fill="white", border.colour="white",
      #                      size=1.8, hjust=1, vjust=0.20)

      #plt <- plt + ggplot2::coord_sf() + ggplot2::labs(x="") +
      #  ggplot2::labs(y="") +
      #  ggplot2::scale_x_discrete(labels = NULL, breaks = NULL) +
      #  ggplot2::scale_y_discrete(labels = NULL, breaks = NULL)


      map <- plt

      #      map + ggplot2::coord_equal()
      #################################
      # general map text, formatting and sizing
      #      suppressMessages(suppressWarnings(
      #        map <- plt + ggplot2::geom_text(data=data.frame(),
      #                                        ggplot2::aes(x=rng.lon[2], y=rng.lat[1]),
      #                                        label=" Map layer: (c) OpenStreetMap/ESRI contributors ",
      #                                        size=1.8, hjust=1, vjust=-0.5) #+
      #          ggplot2::coord_quickmap() +
      #          ggplot2::theme_void()
      #      ))
    } else {
      map <- previous
    }

    out <- suppressMessages(suppressWarnings(
      tubePlot(map, x, y, ...) + ggplot2::coord_sf()
    ))


    out <- out + ggplot2::theme(axis.title.x=ggplot2::element_blank(),
                                axis.text.x=ggplot2::element_blank(),
                                axis.ticks.x=ggplot2::element_blank(),
                                axis.title.y=ggplot2::element_blank(),
                                axis.text.y=ggplot2::element_blank(),
                                axis.ticks.y=ggplot2::element_blank())
    out

  }








##############################
# leafletTubeMap
##############################

# draw maps of tubes using leaflet...

# separated leaftlet and ggplot2 versions of tubeMap 2025-09-18
#

# notes
##########################


# jobs
#############################

# current test
#    dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
#    leafletTubeMap(dd, point=T, polygon=dont.share::caz.bradford)
#    leafletTubeMap(dd, surface=T, point=T)

# standardize args and options so it is more like tubeMap

# add surface fit
#           see
#           https://stackoverflow.com/questions/67537458/creating-a-heatmap-on-r-using-leaflet-function-add-heatmap-or-addheatmap
#           https://gis.stackexchange.com/questions/168886/r-how-to-build-heatmap-with-the-leaflet-package

# leaflet
#   make a static copy of a leaflet output....
#      https://gis.stackexchange.com/questions/299192/saving-leaflet-map-as-image

# quick fix for quarto reports....
#  could not use leafletTubeMap in if in quarto


#' @rdname tube.maps
#' @export

# draw maps of tubes using leaflet...

leafletTubeMap <-
  function(data, x=NULL, y=NULL, plot.type=NULL, ...){

    #plot only intended for tagged or tag-able data...
    d2 <- data

    #args
    .xargs <- dte_ggshellTidyArgs(list(...))
    .xargs <- modifyList(list(grid.borders = 0.05,
                              auto.text = TRUE),
                         .xargs)

    if("leaflet" %in% class(data)){
      previous <- d2
      d2 <- data$dte_data
    } else {
      d2 <- data
      previous <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }
    #do we need/want tagging ?
    d2 <- tagTube(d2)

    ############################
    # x and y handling to enable
    ############################

    # avoiding %>%
    if(is.null(previous)){
      m <- leaflet::leaflet() |>
        leaflet::addProviderTiles("CartoDB.Positron")
      # yes, I am that lazy
      m$dte_data <- d2
    } else {
      m <- previous
    }

    ################################
    # plot.type like tubePlot
    #     BUT for selected plot types
    ################################
    #.check <- c("point", "line", "box", "band", "surface", "smooth", "polygon", "none", "ggsmooth")
    .check <- c("point", "surface", "polygon", "none")
    .tt <- c(plot.type, names(.xargs))
    for(i in .check){
      .tt[grepl(paste("^", i, "[.]", sep=""), .tt)] <- i
    }
    plot.type <- unique(.tt[.tt %in% .check])
    if(length(plot.type)==0){
      plot.type <- "point"
    }

    for(i in plot.type){

      if(i == "polygon"){
        ##########################
        # needs to track args
        ##########################
        if(!is.null(.xargs$polygon)){
          m <- leaflet::addPolygons(m, data=.xargs$polygon)
        }
      }

      if(i == "surface"){
        ##########################
        # currently needs raster added to imports
        ##########################
        # needs to track args
        ##########################
        .dd <- fitTubeModel(d2, tube=".value", inputs=c(".longitude", ".latitude"),
                            new.data="input.ranges", simplify=TRUE, too.far=0.15)
        #print(names(.dd))

        .lat <- unique(.dd$.latitude)
        .lon <- unique(.dd$.longitude)

        r <- raster::raster(xmn = min(.lon, na.rm=TRUE),
                    xmx = max(.lon, na.rm=TRUE),
                    ymn = min(.lat, na.rm=TRUE),
                    ymx = max(.lat, na.rm=TRUE),
                    nrows = length(.lon),
                    ncols = length(.lat))
        .mat <- matrix(.dd$.value.pred, nrow(r), ncol(r),
                       byrow = TRUE)
        .mat  <- .mat[c(ncol(.mat):1),,drop=FALSE]

        raster::values(r) <- .mat
        raster::crs(r) <- raster::crs("+init=epsg:4326")
        pal <- leaflet::colorNumeric("Spectral", rev(pretty(.dd$.value.pred)),
                                     na.color = "#00000000", reverse=T)
        pal2 <- leaflet::colorNumeric("Spectral", rev(pretty(.dd$.value.pred)),
                                     reverse=F)
        m <- leaflet::addRasterImage(m, r, colors = pal, opacity = 0.5) |>
          leaflet::addLegend(pal = pal2, values = pretty(.dd$.value.pred),
                             labFormat = leaflet::labelFormat(transform = function(x) sort(x, decreasing = TRUE)))

      }


      if(i == "point"){
        ##########################
        # needs to track args
        ##########################
        m <- leaflet::addCircleMarkers(m, lng=d2$.longitude, lat=d2$.latitude,
                                       radius=2)
      }

    }
    ########################

      #print(m)
      return(m)
  }






