############################################
#' @title Diffusion Tube Data Plots
############################################

#' @name tube.plots
#' @aliases tube.plots tubePlot tubeTimePlot ggplotTubeShell
#' @description \code{DTEval} uses \code{ggplot2} to generate most plots.
#'
#' Obviously, you are welcome to use any graphics package you know to generate
#' your own plot. In fact, if you want really fine control of plot outputs, we
#' recommend taking the time to learn a graphics package like
#' \code{ggplot}, \code{lattice}, etc. But \code{DTEval} also includes
#' several quick-use wrappers for some commonly used plot types and useful
#' options like grouping and faceting, which can really help with data
#' visualisation. It also includes \code{ggplotTubeShell}, which builds
#' common plot shells for many of these, and handles some of of
#' the generic plot control for functions like \code{\link{testTubePrecision}}
#' and \code{\link{testTubePrecision}}.

# maybe link to ggplot2 and a r help page on graphics for this?

#' @param data Data source, typically a data.frame or similar, to be used to
#' build a plot using ggplot2.
#' @param x,y The names of the data-series to plot on the
#'  X and Y axes, respectively, and assumed to be elements of \code{data}.
#' @param ... Additional arguments. See details below.

#' @details In addition to \code{data}, the main data source for plots,
#' \code{ggplotTubeShell} handles the following common plot arguments:
#'
#' * \code{xlab}, \code{ylab} The X and Y axes labels to use if
#' different from plot defaults.
#'
#'  * \code{group} The name of the data-series to use to group
#'  plotted data with. By default, \code{ggplotTubeShell} assumes
#'  supplied groups are factors if less than 20 unique cases.
#'
#'  * \code{facet} The name of the data-series to use to cut
#'  the data by when generating multiple plot panels. Also provides
#'  an addition \code{facet.type} shortcut to different \code{ggplot2}
#'  facet options: \code{'wrap'} for \code{facet_wrap} (default),
#'  \code{'grid'} for \code{facet_grid} (or 'grid.row' or grid.col' to
#'  specific by row-then-column or column-then-row grid handling,
#'  respectively).
#'
#'  Functions like \code{tubePlot} add layers to this framework to
#'  generate common plots.
#'

## see this about best practice using ggplot2 in a package...
##    (their words not mine..)
## https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html


#' @return \code{tubePlot} is a general purpose plotting functions for
#' diffusion tube data.
#'
#' \code{tubeTimePlot} is a \code{tubePlot} wrapper that adds the tagged
#' sampling date as a second axes if one of \code{x} or \code{y} is
#' supplied.
#'
#' \code{ggplotTubeShell} returns a ggplot object the user then
#' needs to add \code{geom}s to, to build a standard plot.
#'
#' @note Maybe I'm already missing \code{qplot}...


###############################
# documentation notes
###############################

# need to
#######################

###############################
# added
# tidy what follows when done
###############################

# start these functiions again...
#    merge ggplotTubeShell and tubePlot...
#         see notes

# stat args for geoms maybe come from stat_[...] functions
#    but be careful - there is a lot there...




##


#    reference and link to ggplot2... and/or plotting more generally in R

#    think about default colours
#       The default ggplot2 color for a continuous scale is a blue gradient,
#       specifically a low value of dark blue (#132B43) and a high value of
#       light blue (#56B1F7). This is generated by the default
#       scale_color_gradient() or scale_fill_gradient() functions,
#       which use the seq_gradient_pal() function from the scales package
#       to create the color steps.

# think about
#######################

# decide and document col/colour handling

# decide and document palette and fill.palette handling

# decide and document rotate.x.axes

# decide and document key.position and key.direction



#############################
# code notes - general
#############################

# removed full imports
## #' @import dplyr, etc
## now specifying directly in code, ggplot2::ggplot, etc


# most urgent
############################

# possible issue with point.count when it is same as one of the two axes...
#    see
#      tubeTimePlot(tagTube(dont.share::dt.bradford.2), y="measurement", plot.type = "point.count", size="measurement")
#    and what I think it should look like...
#       tubeTimePlot(tagTube(dont.share::dt.bradford.2), y="measurement", plot.type = "point.count", size=".latitude")
#    related
#       using stat for similar with bar plots
#          see this about stat_... functions
#          https://yjunechoe.github.io/posts/2020-09-26-demystifying-stat-layers-ggplot2/
#       might be an easier option



# think about
##############################

# think about an option to kill the legend...
#    maybe do by default if group or col are factors or characters and too large
#       but they add a kill option

# option rotate axes labels

# control of scale free, free_x, free_y, etc...
#     is currently by ggplotTubeShell that passes scales to the ggplot2::facet_[whatever]
#         this is part of a facet... formals only do.call
#         might fall over is scales is allowed but one of the geoms when used through
#            tubePlot



# think about extending palette to fill?
#    [might now be done... via ggplotTUbeShell?]
#    playing with this...
#    tubePlot(dont.share::dt.bradford.2, plot.type="site", palette=c("white", "green")) + ggplot2::geom_density_2d_filled(breaks=10^(0:10)

# think about an option to pass argument to just one layer
#    can obviously do that in a function...
#        but not from a tubePlot call...

# like something like smooth but not as talkative...

#



####################################
# plotTube
####################################

# common plots wrapper

########################
# second draft ???
########################

# re-built ggplotTubeShell to better handle mapping/aes terms

# proposing making tubePlot the standard plot
# then tubeTimePlot a variation that by default sets x  to date
# also think about making tubeSitePlot tubeMap without the map...



#####################
# notes
#####################

# NEED to go through these notes....
#    (some might be done/fixed now...)

# using ggplotTubeShell
#     dte_ggshellTestArgs
#     dte_ggshellAddGeom
#     getTubeX and checkTubeData

# once we have range of required plots agreed
#     we should be able to simplify/automate a lot of this

# playing with

# nice visualizations....
#    https://www.nature.com/articles/s41467-018-03297-7

# see this about irregular data
#    https://stackoverflow.com/questions/37529116/how-to-plot-a-heat-map-with-irregular-data-in-ordinates-in-ggplot

# also
#    tubePlot(tagTube(dont.share::dt.bradford.2), x=".longitude", y=".latitude", palette=c("white", "green")) + ggplot2::geom_density_2d_filled(breaks=10^(0:10)) +ggplot2::xlim(-2.5,-1) + ggplot2::ylim(53.7, 54)
#       # needs three colours because it is default fill.pallete because no fill in call...
#           # and every if there were, the geom would ignore it because it uses a z term...

# saw this on over.plotting
# https://bookdown.dongzhuoer.com/hadley/ggplot2-book/overplotting

# also
#    tubePlot(tagTubeDate(dd), x=".date", y=".latitude", surface.fill=".value")
#       dies because .date has two names...

# update based on current tubeMap
#    previous tubePlot now unexported tubePlot.old
#
# dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
# dd$.year <- format(tagTubeDate(dd)$.date, "%Y")
# tubePlot(dd, x=".longitude", y=".latitude", palette=c("white", "green"), point.col=".value")

#' @rdname tube.plots
#' @export

tubePlot <-
  function(data, x=NULL, y=NULL, ...){

    #setup
    ####################
    #args
    .xargs <- list(...)
    .xargs <- dte_ggshellTidyArgs(.xargs)
    #data
    if("ggplot" %in% class(data)){
      previous <- data
      d2 <- data$data
    } else {
      d2 <- data
      previous <- NULL
    }
    if("new.data" %in% names(.xargs)) {
      d2<-.xargs$new.data
    }

    # x/y handling
    ####################################
    # do we want .index option handling...
    ####################################
    if(is.null(x) & is.null(y)){
      stop("[tubePlot]> need at least one of 'x' and 'y'...",
           call.=FALSE)
    }
    if(is.null(x)){
      x <- ".default"
      d2$.default <- ""
      if(!"xlab" %in% names(.xargs)){
        .xargs$xlab <- ""
      }
    }
    if(is.null(y)){
      y <- ".default"
      d2$.default <- ""
      if(!"ylab" %in% names(.xargs)){
        .xargs$ylab <- ""
      }
    }
    d2[, x] <- getTubeX(d2, x, if.err = "stop<<tubePlot>>x")
    d2[, y] <- getTubeX(d2, y, if.err = "stop<<tubePlot>>y")

    #############################
    # without any this dies if length(names(.xargs)) > 1
    #############################
    # currently not facetting tubeMaps
#    if(length(names(.xargs))>0 && any(grepl("^facet", names(.xargs)))){
#      stop("[tubeMap] Sorry, map facet currently disabled",
#           call. = FALSE)
#    }
    ########################
    #

    if(!"grid.borders" %in% names(.xargs)){
      .xargs$grid.borders <- 0.05
    }

    ## build map layer
    ## (if not already a plot...)
    ###################
    if(is.null(previous)){
      # stuff ggplotTubeShell deals with...
      .ggshell <- c("facet.type", "xlab", "ylab",
                    "auto.text", "palette", "fill.palette", "map.args",
                    "key.position", "key.direction", "rotate.x.axes")
      #.safe <- .xargs[names(.xargs) %in% c(.ggshell, "colour", "group")]
      #.safe <- modifyList(list(data=data, x=x, y=y), .safe)
      .all <- modifyList(list(data=d2, x=x, y=y), .xargs)
      plt <- do.call(ggplotTubeShell, .all)
      # remove stuff handled by ggplotTubeShell
      .xargs <- .xargs[!names(.xargs) %in% .ggshell]
      # putting x and y back in, in case we have to kill one of the mappings...
      #    plot.type="hist" does this...
      .xargs <- modifyList(list(x=x, y=y),
                           .xargs)
    } else {
      plt <- previous
    }

    # add polygon
    if(any(grepl("^polygon", names(.xargs)))){
      ##########################
      #testing this tidy
      #    Holding code because it is very sensitive to ordering
      #.xargs2 <- .xargs[grepl("^polygon[.]", names(.xargs))]
      #names(.xargs2) <- gsub("polygon[.]", "", names(.xargs2))
      #names(.xargs2)[names(.xargs2) %in% c("col", "color")] <- "colour"
      #.xargs2 <- .xargs2[!duplicated(names(.xargs2), fromLast=TRUE)]
      #.xargs2 <- modifyList(.xargs, .xargs2)
      .xargs2 <- dte_ggshellTidyArgs(.xargs, "polygon")
      if(.xargs2$..test=="OK"){
        .xargs2 <- modifyList(.xargs2, list(x="X", y="Y"))
        ##########################
        # to think about...
        #    this currently needs polygon to be a sf polygon...
        #        BUT polygon could be a different object type ...
        #        OR polygon could be true... then you would use the data as polygon source
        #            can't colour a polygon by palette at moment
        .xargs2$polygon <- as.data.frame(sf::st_coordinates(.xargs2$polygon))
        drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPolygon)]
        plt <- dte_ggshellAddGeom(.xargs2, .xargs2$polygon, plt,
                                  ggplot2::geom_polygon,
                                  defaults = list(na.rm=TRUE, colour="blue",
                                                  fill="blue", alpha=0.25),
                                  drops = drops)
      }
    }

    # add surface
    ############################
    # this need tidying for contour and col handling
    # issue this error because col terms is fitted...
    # tubeMap(a, point=T, surface.fill=".value", too.far=0.1, grid.resolution=400, contour=T, point.col=".value", polygon=dont.share::caz.bradford, grid.borders=0.05, col=".value")
    #
    if(any(grepl("^surface", names(.xargs)))){
      #just arg should trigger this contour ??
      .xargs2 <- dte_ggshellTidyArgs(.xargs, "surface")
      .xargs2.test <- dte_ggshellTestArgs(.xargs2, d2)
      .test <- names(.xargs2.test[.xargs2.test=="data"])
      .test <- .test[.test %in% c("fill", "z", "colour", "contour")]
      if(length(.test)>0){
        .fit.args <- modifyList(list(data=d2, tube=.xargs2[[.test[1]]],
                                     inputs=c(x,y), by=c(.xargs$group, .xargs$facet),
                                     simplify=TRUE, new.data="input.ranges"),
        #################################
        # could generalise next bit ???
        #################################
                                .xargs2[names(.xargs2) %in% c("too.far", "model",
                                                              "simplify",
                                                              "force.positive",
                                                              "grid.resolution",
                                                              "grid.borders")])
        .d2 <- do.call(fitTubeModel, .fit.args)
        .xargs2[[.test[1]]] <- paste(.xargs2[[.test[1]]], ".pred", sep="")
        if(.xargs2$..test=="OK"){
          .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
          ##########################
          # if fill in there
          if("fill" %in% names(.xargs2)){
            .xargs2$fill <- .xargs2[[.test[1]]]
            drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomTile)]
            drops <- c(drops, "col", "color", "colour")
            plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                      ggplot2::geom_tile,
                                      defaults = list(na.rm=TRUE),
                                      drops = drops)
          }
          if("contour" %in% names(.xargs2)){
            ###################
            # fix for contour.[whatever]
            # maybe contour should be black if no fill and no col..?
            .xargs2$z <- .xargs2[[.test[1]]]
            drops <-  names(.xargs2)[!names(.xargs2) %in% c(dte_GeomArgs(ggplot2::GeomContour),
                                                            "z")]
            drops <- c(drops, "fill", "alpha")
            plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                      ggplot2::geom_contour,
                                      defaults = list(na.rm=TRUE,
                                                      colour="white"),
                                      drops = drops)
            plt <- dte_ggshellAddGeom(.xargs2, .d2, plt,
                                      metR::geom_text_contour,
                                      defaults = list(na.rm=TRUE,
                                                      colour="white"),
                                      drops = drops)
          }

        }

      }

    }

    #add point(s)
    if(any(grepl("^point", names(.xargs)))){
      ##########################
      # testing this tidy
      .xargs2 <- dte_ggshellTidyArgs(.xargs, "point")
      if(.xargs2$..test=="OK"){
        .xargs2 <- modifyList(list(x=x, y=y), .xargs2)
        ##########################
        drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPoint)]
        plt <- dte_ggshellAddGeom(.xargs2, d2, plt,
                                  ggplot2::geom_point,
                                  defaults = list(na.rm=TRUE),
                                  drops = drops)
      }
    }

    ##################
    # to do
    #################
    # point mean, count, etc...
    # add faceting
    #     might be a big job ...
    #        the openstreetmap::auto.plot does not want to facet
    # add grouping ???
    # add/tidy structure - palette, legend, ect...

    #
    return(plt)

  }


tubePlot.old <-
  function(data, x=NULL, y=NULL, plot.type="point",
           ...){

    # might want to tidy this once methods are finalised

    # setup
    .xargs <- list(...)
    #what to do about col/colour...?
    #   currently using this cludge in both tubePlot and ggplotTubeShell
    #      and assuming color hereafter...
    names(.xargs)[names(.xargs) %in% c("col", "color")] <- "colour"
    .xargs <- .xargs[!duplicated(names(.xargs), fromLast=TRUE)]


    #need this if facet source is also used for other args, e.g. col...
    if(!is.null(.xargs$facet)){
      data$..facet <- getTubeX(data, .xargs$facet)
      .xargs$facet <- "..facet"
    }

    # x/y handling
    ####################################
    # do we want .index option handling...
    ####################################
    if(is.null(x) & is.null(y)){
      stop("[tubePlot]> need at least one of 'x' and 'y'...",
           call.=FALSE)
    }
    if(is.null(x)){
      x <- ".default"
      data$.default <- ""
      if(!"xlab" %in% names(.xargs)){
        .xargs$xlab <- ""
      }
    }
    if(is.null(y)){
      y <- ".default"
      data$.default <- ""
      if(!"ylab" %in% names(.xargs)){
        .xargs$ylab <- ""
      }
    }
    data[, x] <- getTubeX(data, x, if.err = "stop<<ggplotTubeShell>>x")
    data[, y] <- getTubeX(data, y, if.err = "stop<<ggplotTubeShell>>y")

    .xargs.test <- dte_ggshellTestArgs(.xargs, data)
    .dd <- .xargs[names(.xargs) %in% names(.xargs.test[.xargs.test=="data"])]
    data <- checkTubeData(data, unlist(.dd))
    .xargs.test <- dte_ggshellTestArgs(.xargs, data)

    # main args (x,y,group, facet) are checked
    #     BUT ALSO might want to run all .xargs
    #         identified as data through checkTubeData ???
    #         to allow stuff like col = "factor(measurement)", etc... ???

    if(length(plot.type)==1){
      plot.type <- unlist(strsplit(plot.type, ","))
    }
    plot.type <- tolower(gsub(" ", "", plot.type))

    ################################
    # overplot.action
    ################################
    # moving calculation into layers where it is used
    # BUT calculating parameters early because they could be used multiple times...
    #    so calculating .by and .x for use in calcTubeStat
    #       data <- suppressWarnings(calcTubeStat(data, .x, by =.by))
    #    AND
    #       stat <- function(x) { list(mean=mean(x, na.rm=TRUE))
    #    BUT only running this when using it...
    # SEE point.mean as example...

    #if(!is.null(overplot.action)){
      .by <- c(x, y, .xargs$facet, .xargs$group)
      .x <- c()     ##### temp setting
      if(length(.xargs)>0){
        for(i in 1:length(.xargs)){
          #print(.xargs[[i]]) - value
          #print(names(.xargs)[i]) - name
          if(.xargs.test[[i]]=="data"){
            if(!is.numeric(getTubeX(data, .xargs[[i]]))){
              .by <- c(.by, .xargs[[i]])
            } else {
              .x <- c(.x, .xargs[[i]])
            }
          }
        }
      }
      .by <- unique(.by)
      .x <- unique(.x[!.x %in% .by])
      if(length(.x)<1){
        #add dummy
        data$..dummy <- 1
        .x="..dummy"
      }
    #  names(data) <- gsub("[.]mean", "", names(data))
    #}

    ##################################
    # main plot
    ##################################
    #  should be able to tidy this once range of plots agreed...

    # stuff ggplotTubeShell deals with...
    .ggshell <- c("facet", "facet.type", "xlab", "ylab",
                  "auto.text", "palette", "fill.palette", "map.args",
                  "key.position", "key.direction", "rotate.x.axes")
    #.safe <- .xargs[names(.xargs) %in% c(.ggshell, "colour", "group")]
    #.safe <- modifyList(list(data=data, x=x, y=y), .safe)
    .all <- modifyList(list(data=data, x=x, y=y,
                            map.args = c("x", "y")), .xargs)
    out <- do.call(ggplotTubeShell, .all)
    # remove stuff handled by ggplotTubeShell
    .xargs <- .xargs[!names(.xargs) %in% .ggshell]
    # putting x and y back in, in case we have to kill one of the mappings...
    #    plot.type="hist" does this...
    .xargs <- modifyList(list(x=x, y=y),
                         .xargs)

    #################################
    # add plot layers
    #################################

    .unknown <-c()
    for (i in plot.type){
      temp <- FALSE
      # template
      # if(i==...){
      #   temp <- TEMP
      #   if we change data make d2
      #   if we chande .xargs make .xargs2
      #       or you'll get both all other any follow-on layers...
      # }




      #bar chart
      if(i %in% c("bar", "bar.count", "bar.mean", "bar.sum")){
        # largely untested
        # local rules
        #   if stat type not set e.g. bar not bar.[whatever]
        #        only one of x or = bar.count
        #        if both bar.sum
        #   otherwise function forced by bar.[whatever if known]
        #   IF STAYING
        #        NEEDS documenting and possibly WARNINGS...
        # TO LOOK INTO...
        #   if x and y and no group might need to make one group as well
        #     check with both tubePlot and tubeTimePlot if changing this...
        #   difference in colouring of geom_bar and geom_col
        #       check documentation on these
        #          NOW using geom_bar with different stats to avoid this...
        #          BUT this handling might need documenting and warnings...
        #   rescale x and y can kill this
        #       see
        #          tubePlot(dt.york, x="month", y="measurement",
        #                   plot.type = "bar.count", fill="month") +
        #          ggplot2::scale_y_continuous(limits=c(3000, 6000))
        #   allowing/testing position = "dodge", "fill", "stack"
        #       if staying this NEEDS documenting and maybe warning messages...
        #          position = "identity" also an option That is the do nothing
        #                  WHICH overplots bars....


        temp <- TRUE
        .xargs2 <- .xargs # might want the group going to all
        if(".default" %in% c(x,y)){
          # this is a bar plot...
          # might have to kill this is mixing with other plots???
          if(x==".default"){
            out$mapping$x <- NULL
            .xargs2$x <- "..dummy"
            data$..dummy <- 1
          } else {
            out$mapping$y <- NULL
            .xargs2$y <- "..dummy"
            data$..dummy <- 1
          }
          if(i=="bar"){
            ..fun <- function(x) { length(x[!is.na(x)]) }
          }
        } else {
          if(i=="bar"){
            ..fun <- function(x) { sum(x[!is.na(x)]) }
          }
        }
        if(i=="bar.mean"){
          ..fun <- function(x) { mean(x[!is.na(x)]) }
        }
        if(i=="bar.count"){
          ..fun <- function(x) { length(x[!is.na(x)]) }
        }
        if(i=="bar.sum"){
          ..fun <- function(x) { sum(x[!is.na(x)]) }
        }
          .xargs2$stat <- "summary"
          .xargs2$fun <- ..fun
          drops <-  names(.xargs2)[!names(.xargs2) %in% c(dte_GeomArgs(ggplot2::GeomBar),
                                                          "stat", "fun", "position")]
          out <- dte_ggshellAddGeom(.xargs2, data, out,
                                    ggplot2::geom_bar,
                                    defaults = list(na.rm=TRUE,
                                                    colour="black", fill="grey"),
                                    drops = drops)

      }



      # box and whisker plot
      if(i=="box"){
        # largely untested
        # local rules
        #   if x and y and no group make one group as well
        #     check with both tubePlot and tubeTimePlot if changing this...
        #       example tubeTimePlot(tagTube(dont.share::dt.bradford.2), y="measurement", plot.type = "box")
        #     this dies if both x and y are numeric...
        #       possible next steps/options
        #          use whichever has least unique elements as group ???
        #          allow option like orientation or force ???
        # could be boxplot args I don't know about
        #     or allow via dte_ggshellAddGeom ???
        temp <- TRUE
        .xargs2 <- .xargs # might want the group going to all
        data2 <- data
        if(!".default" %in% c(x,y)){
          if(!"group" %in% names(.xargs2)){
            ###########################
            # note
            ###########################
            # this'll die if both are numeric...
            .test <- unique(unlist(.xargs2[names(.xargs.test[.xargs.test=="data"])]))
            if(is.numeric(getTubeX(data, x))){
              data2$..group <- paste(getTubeX(data2, y), data2[[.test]])
            } else {
              data2$..group <- paste(getTubeX(data2, x), data2[[.test]])
            }
            .xargs2$group <- "..group"
          }
        }
        drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomBoxplot)]
        out <- dte_ggshellAddGeom(.xargs2, data2, out,
                                  ggplot2::geom_boxplot,
                                  defaults = list(na.rm=TRUE, fill="grey"),
                                  drops = drops)
      }



      #histogram
      if(i=="hist"){
        # have to kill one of x or y for this
        #    so it does not play nicely with plots that do at the moment...
        # need to allow statistical args
        #    ideally do better than drops below
        # if mapped aesthetics are numerics may need to group or make factor
        #    see
        #        tubePlot(dt.york, x="measurement", plot.type = "hist",
        #                 facet="month", fill="factor(CalendarYear)",
        #                 group="CalendarYear")
        # other axes currently labelled count by default...
        #     need to tidy this if we ...

        temp <- TRUE
        if(!".default" %in% c(x, y)){
          stop("[tubePlot] sorry; plot.type 'hist' only allows one of x or y...",
               call. = FALSE)
        }
        .xargs2 <- .xargs
        if(x==".default"){
          out$mapping$x <- NULL
          .xargs2$x <- NULL
          if(out$labels$x == ""){
            out$labels$x <- "count"
          }
        }
        if(y==".default"){
          out$mapping$y <- NULL
          .xargs2$y <- NULL
          if(out$labels$y==""){
            out$labels$y <- "count"
          }
        }
        drops <- names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomBar)]
        drops <- drops[!drops %in% c("bins", "binwidth")]
        out <- dte_ggshellAddGeom(.xargs2, data, out,
                                  ggplot2::geom_histogram,
                                  defaults = list(na.rm=TRUE, colour="black", fill="grey",
                                                  bins=30),
                                  drops = drops)
      }

      #scatter plot 'point'
      if(i %in% c("point", "point.mean", "point.count")){
        #  has overplotting options point.mean and point.count
        #  possible issue
        #     tubeTimePlot(tagTube(dont.share::dt.bradford.2),
        #                   y="measurement", group="year_of_measurement",
        #                   size="measurement",
        #                   plot.type = "point.count")
        #     is not what you would expect
        #         because size="measurement" is the average of overplot points
        #         when measurement is also one of the axes...
        #     can pass ..dummy.count unless as other plot arg...I try to recolour...
        #     might have to make a dummy of the duplicated axes to use in
        #         point.mean/count
        temp <- TRUE
        if(i == "point.mean"){
          .stat <- function(x) { list(mean=mean(x, na.rm=TRUE)) }
          d2 <- suppressWarnings(calcTubeStat(data, .x, stat=.stat, by =.by))
          #names(d2) <- gsub("[.]mean", "", names(d2))
          .xargs2 <- .xargs
          .xargs2[.xargs2 %in% .x] <- paste(.xargs2[.xargs2 %in% .x], ".mean", sep="")
          ##ignoring if nothing is averaged
          ##if("..dummy.mean" %in% names(d2) & !"size" %in% names(.xargs2)){
          ##  .xargs2$size = "..dummy.mean"
          ##}
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPoint)]
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_point,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)

        }
        if(i == "point.count"){
          .stat <- function(x) { list(count=length(x[!is.na(x)])) }
          d2 <- suppressWarnings(calcTubeStat(data, .x, stat=.stat, by =.by))
          .xargs2 <- .xargs
          .xargs2[.xargs2 %in% .x] <- paste(.xargs2[.xargs2 %in% .x], ".count", sep="")
          if("..dummy.count" %in% names(d2) & !"size" %in% names(.xargs2)){
            .xargs2$size = "..dummy.count"
          }
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomPoint)]
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_point,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
        }
        if(i=="point"){
        drops <-  names(.xargs)[!names(.xargs) %in% dte_GeomArgs(ggplot2::GeomPoint)]
        out <- dte_ggshellAddGeom(.xargs, data, out,
                                 ggplot2::geom_point,
                                 defaults = list(na.rm=TRUE),
                                 drops = drops)
        }
      }

      #smooth
      if(i=="smooth"){
        temp <- TRUE
        .xargs2 <- .xargs
        data2 <- data
        drops <-  names(.xargs)[!names(.xargs) %in% dte_GeomArgs(ggplot2::GeomSmooth)]
        out <- dte_ggshellAddGeom(.xargs, data, out,
                                  ggplot2::geom_smooth,
                                  defaults = list(na.rm=TRUE,
                                                  formula = y ~ x, method = loess),
                                  drops = drops)
      }


      #surface
      # current test
      ## dd <- tagTube(dont.share::dt.bradford.2); dd <- dd[dd$.longitude<0,]
      ## tubePlot(dd, x="longitude", y="latitude", z=".value", plot.type = "surface", fill=".value", colour="white", too.far=0.1, alpha=0.5)

      ## tubePlot(dd, x="longitude", y="latitude", fill=".value", plot.type = "surface", too.far=0.1)
      ## next is interesting .... it is keeping .value from the points...
      ## maybe think about surface.fill ???
      ## tubePlot(dd, x="longitude", y="latitude", fill=".value", plot.type = c("surface.new", "point"), too.far=0.1, palette=1:5)
      ## raster gives a warning if you remove records
      ## how about if you NA them and set na.col to transparent?
      ## maybe turn off group...
      ## look how I did it for the animations...
      ##    I think that was better...
      ## I would like the smooth function to be user set-able...
      ##    So they can Krieg, etc...
      ## I should add mgcv to imports if I keep too.far ???
      ## expand the x and y ranges of the points ??? in case anyone does when fitting a surface ???
      ## alpha not tracked by colour/fill legend...
      if(i %in% c("surface")){
        temp <- TRUE
        .stat <- function(x) { list(smooth=mean(x, na.rm=TRUE)) }
        d2 <- suppressWarnings(calcTubeStat(data, .x, stat=.stat, by =.by))
        .xargs2 <- .xargs
        .xargs2[.xargs2 %in% .x] <- paste(.xargs2[.xargs2 %in% .x], ".smooth", sep="")

        ..x <- getTubeX(d2, .by[1])
        ..x <- seq(min(..x, na.rm=TRUE), max(..x, na.rm=TRUE), length=200)
        ..y <- getTubeX(d2, .by[2])
        ..y <- seq(min(..y, na.rm=TRUE), max(..y, na.rm=TRUE), length=200)
        .dd <- expand.grid(..x, ..y)
        names(.dd) <- .by[1:2]
        .tmp <- names(d2)[!names(d2) %in% .by[1:2]]
        if(!"..facet" %in% names(d2)){
          d2$..facet <- "default"
        }
        ans <- lapply(unique(d2$..facet), function(x){
          .d2 <- d2[d2$..facet==x, ]
          for(ii in c("z")){
            if(ii %in% names(.xargs2)){
              #.ff <- paste(.xargs2[[ii]], "~", paste(.by[1], .by[2], sep="+"), sep="")
              .ff <- paste(.xargs2[[ii]], "~te(", paste(.by[1], .by[2], sep=","), ")", sep="")
              print(.ff)
              print(names(.d2))
              mod <- mgcv::gam(as.formula(.ff), data=.d2)
              #.dd[[.xargs2[i]]] <- NA
              .dd$.prd <- as.vector(predict(mod, newdata=.dd))
              names(.dd)[names(.dd)==".prd"] <- .xargs2[[ii]]
            }
          }
          if("too.far" %in% names(.xargs2)){
            ex.tf <- mgcv::exclude.too.far(.dd[,.by[1]], .dd[,.by[2]], .d2[, .by[1]],
                                           .d2[, .by[2]], dist = .xargs2$too.far)
            #.dd$.value.mean[ex.tf] <- NA
            .dd <- .dd[!ex.tf,]
          }
          .dd$..facet <- x
          .dd
        })
        .dd <- do.call(rbind, ans)
        print(names(.dd))


        ## see also
        ## geom_raster(interpolate=TRUE)
        ## gets
        ## Warning message:
        ## Raster pixels are placed at uneven horizontal intervals and will be shifted
        #  ℹ Consider using `geom_tile()` instead.

        #turning off these at moment
        # so plot is a dead end...

        #this needs fill set
        if("fill" %in% names(.xargs2)){
          drops <-  names(.xargs2)[!names(.xargs2) %in% c(dte_GeomArgs(ggplot2::GeomTile))]
          drops <- c(drops, "colour")
          out <- dte_ggshellAddGeom(.xargs2, .dd, out,
                                    ggplot2::geom_tile,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
        }

        #this needs z set
        if("colour" %in% names(.xargs2)){
          #.xargs2$z <- .xargs2$fill
          drops <-  names(.xargs2)[!names(.xargs2) %in% c(dte_GeomArgs(ggplot2::GeomContour), "z")]
          drops <- c(drops, "fill", "alpha")
          out <- dte_ggshellAddGeom(.xargs2, .dd, out,
                                    ggplot2::geom_contour,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
          out <- dte_ggshellAddGeom(.xargs2, .dd, out,
                                    metR::geom_text_contour,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
        }

      }



      #ribbons
      if(grepl("stat.ribbon", i)){
        #various stat.ribbons
        # in-development
        #    dte_GeomArgs(ggplot2::GeomRibbon)
        #       returns "x|y"         "ymin|xmin"   "ymax|xmax"   "colour"      "fill"        "linewidth"   "linetype"
        #               "alpha"       "na.rm"       "orientation" "group"
        #       so y and y hidden ...
        #           currently using unlist(strsplit(t1, "[|]")) to unhide these
        #                (in xxx.r dte_GeomArgs)
        #    grouping as copy of fill if group not there and but fill is data
        #       might not be complete fix ... see below
        # NEED TO LOOK AT following
        #    this kills it
        #         tubeTimePlot(dt.york, y="measurement", plot.type="stat.ribbon",
        #                      ribbon.probs=c(0.1,0.5, 0.9), fill="factor(CalendarYear)",
        #                      facet="month")
        #             BUT resetting the group to the facet might save this... ??
        #
        #     ribbons need both x and y
        #     check I have x.ribbon and y.stat.ribbon
        #          might be a simpler way of do this ???
        #     currently dies if the ribbon term stat term is not numeric...
        temp <- TRUE
        # note: I need to mess with stat.ribbon...
        local <- i
        #set to "x.stat.ribbon" or "y.stat.ribbon" if not set
        if(grepl("^stat[.]ribbon", local)){
          local <- if(is.numeric(getTubeX(data, x))){
               paste("y.", local, sep="")
          } else {
               paste("x.", local, sep="")
          }
        }
        ##########################
        # using ribbon.probs because it aligns with the quantile error
        ##########################
        .q <- if(is.null(.xargs$ribbon.probs)){
          c(0, 0.5, 1)
        } else {
          .xargs$ribbon.probs
        }
        if(grepl("^x[.]", local)){
          ##########################
          # anything here needs to be duplicated above...
          # (when sorted we should be able to rationalise a lot of these)
          ##########################
          .stat <- function(x) { list(y.mid=stats::quantile(x, probs=.q[2], na.rm=TRUE, names=FALSE),
                                      y.low=stats::quantile(x, probs=.q[1], na.rm=TRUE, names=FALSE),
                                      y.hi=stats::quantile(x, probs=.q[3], na.rm=TRUE, names=FALSE)) }
          d2 <- suppressWarnings(calcTubeStat(data, y, stat=.stat, by=
                                                unique(c(.x,.by)[!c(.x,.by) %in% y])))
          d2 <- d2[order(getTubeX(d2, x)),]
          .xargs2 <- .xargs
          if("colour" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs.test["colour"]=="data"){
              .xargs2$group <- .xargs$colour
            }
          }
          if("fill" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs.test["fill"]=="data"){
              .xargs2$group <- .xargs$fill
            }
          }
          .xargs2$y <- paste(y, ".y.mid", sep="")
          .xargs2$ymin <- paste(y, ".y.low", sep="")
          .xargs2$ymax <- paste(y, ".y.hi", sep="")
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRibbon)]
          drops <- c(drops, "colour")
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_ribbon,
                                    defaults = list(na.rm=TRUE,
                                                    fill="grey", alpha=0.5),
                                    drops = drops)
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomLine)]
          drops <- c(drops, "alpha")
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_line,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)

        }
        if(grepl("^y[.]", local)){
          ##########################
          # anything here needs to be duplicated above...
          # (when sorted we should be able to rationalise a lot of these)
          ##########################
          .stat <- function(x) { list(x.mid=stats::quantile(x, probs=.q[2], na.rm=TRUE, names=FALSE),
                                      x.low=stats::quantile(x, probs=.q[1], na.rm=TRUE, names=FALSE),
                                      x.hi=stats::quantile(x, probs=.q[3], na.rm=TRUE, names=FALSE)) }
          d2 <- suppressWarnings(calcTubeStat(data, x, stat=.stat, by=
                                                unique(c(.x,.by)[!c(.x,.by) %in% x])))
          d2 <- d2[order(getTubeX(d2, y)),]
          .xargs2 <- .xargs
          if("colour" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a col we need a group
            # BUT only copy if col is in data copy col
            if(.xargs.test["colour"]=="data"){
              .xargs2$group <- .xargs$colour
            }
          }
          if("fill" %in% names(.xargs2) & !"group" %in% names(.xargs2)){
            # if we have a fill we need a group
            # BUT only copy if fill is in data copy fill
            if(.xargs.test["fill"]=="data"){
              .xargs2$group <- .xargs$fill
            }
          }
          .xargs2$x <- paste(x, ".x.mid", sep="")
          .xargs2$xmin <- paste(x, ".x.low", sep="")
          .xargs2$xmax <- paste(x, ".x.hi", sep="")
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomRibbon)]
          drops <- c(drops, "colour")
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_ribbon,
                                    defaults = list(na.rm=TRUE,
                                                    fill="grey", alpha=0.5),
                                    drops = drops)
          drops <-  names(.xargs2)[!names(.xargs2) %in% dte_GeomArgs(ggplot2::GeomLine)]
          drops <- c(drops, "alpha")
          out <- dte_ggshellAddGeom(.xargs2, d2, out,
                                    ggplot2::geom_path,
                                    defaults = list(na.rm=TRUE),
                                    drops = drops)
        }
      }



#      ###########################
#      # ghost needs more work if
#      #    averaging is used...
#      if(i=="ghost"){
#      #  #standard point
#        temp <- TRUE
#        d2 <- data[names(data) != "..facet"]
#        out <- dte_ggshellAddGeom(.xargs, d2, out,
#                                 ggplot2::geom_point,
#                                 defaults = list(na.rm=TRUE),
#                                 holds = list(colour = "grey"))
#      }

#      if(i=="bin2d"){
#        #standard count - might not stay
#        temp <- TRUE
#        out <- dte_ggshellAddGeom(.xargs, data, out,
#                                  ggplot2::geom_bin2d, list(na.rm=TRUE),
#                                  c())
#      }
#      if(i=="hex"){
#        #standard count - might not stay
#        temp <- TRUE
#        out <- dte_ggshellAddGeom(.xargs, data, out,
#                                  ggplot2::geom_hex, list(na.rm=TRUE),
#                                  c())
#      }

      if(!temp){
        .unknown <- c(.unknown, i)
      }
    }

    # what was ignored
    if(length(.unknown)>0){
      warning("[tubePlot]> did not understand/ignoring plot.type : ",
              paste(.unknown, sep=",", collapse=","),
              call.=FALSE)
    }

    # returned plot
    return(out)
  }




####################################
# tubeTimePlot
####################################

# tubePlot wrapper that adds .date was other axes if one already set...

# to time about
###################################

# default x/ylab if x/y set ?

#' @rdname tube.plots
#' @export


tubeTimePlot <-
  function(data, x=NULL, y=NULL,
           ...){

    #setup
    .xargs <- list(...)
    #data
    if("ggplot" %in% class(data)){
      data$data <- tagTubeDate(data$data)
    } else {
      data <- tagTubeDate(data)
    }
    #if("new.data" %in% names(.xargs)) {
    #  data<-.xargs$new.data
    #  # have to assume they have this sorted
    #}
    ###################
    # time plot currently needs one of x or y set
    # might be a few cases where this could/should be allowed?
    #    tubeTimePlot(dt.york, plot.type = "bar", col="month")
    #    others...
    if(is.null(x) & !is.null(y)){
      x <- ".date"
    }
    if(is.null(y) & !is.null(x)){
      y <- ".date"
    }
    tubePlot(data = data, x = x, y = y,
             ...)

}




#' @rdname tube.plots
#' @export



ggplotTubeShell <-
  function(data, x=NULL, y=NULL, ...){

    #poor man's quickplot...
    ################################

    #.xargs
    .xargs <- list(...)

    #what to do about this...?
    #using in tubePlot and ggplotTubeShell
    names(.xargs)[names(.xargs) %in% c("col", "color")] <- "colour"
    #trusting last rather than first version of any argument
    #   that is duplicated...
    .xargs <- .xargs[!duplicated(names(.xargs), fromLast=TRUE)]

    # x and y handling
    # indexing if one missing
    # could also check .xargs for an x or x passed down... ?
    if(is.null(x) & is.null(y)){
      stop("[ggplotTubeShell]> Sorry, need at least one of: x,y \n",
           call.=FALSE)
    }
    if(is.null(y)){
      data$.index <- 1:nrow(data)
      y <- ".index"
    } else {
      if(is.null(x)){
        data$.index <- 1:nrow(data)
        x <- ".index"
      }
    }
    data[, x] <- getTubeX(data, x, if.err = "stop<<ggplotTubeShell>>x")
    data[, y] <- getTubeX(data, y, if.err = "stop<<ggplotTubeShell>>y")

    .xargs.test <- dte_ggshellTestArgs(.xargs, data)
    map.args <- if("map.args" %in% names(.xargs)){
      .xargs$map.args
    } else {
      names(.xargs.test[.xargs.test=="data"])
    }

    if(!"xlab" %in% names(.xargs)){
      .xargs$xlab <- x
    }
    if(!"ylab" %in% names(.xargs)){
      .xargs$ylab <- y
    }
    if("auto.text" %in% names(.xargs) && .xargs$auto.text){
      .xargs$xlab <- dte_quickText(.xargs$xlab, TRUE)
      .xargs$ylab <- dte_quickText(.xargs$ylab, TRUE)
    }

    ##########################################
    #these currently ignore anything not expected...
    #########################################
    if("group" %in% names(.xargs)){
      data <- checkTubeData(data, x=.xargs$group, n.x=1,
                            if.err = "stop<<ggplotTubeShell>>group")
      #if unique(group) less than 20 treat as factor...
      if(length(unique(data[[.xargs$group]]))<20){
        data[[.xargs$group]] <- factor(data[[.xargs$group]], ordered=TRUE)
      }
    }
    if("facet" %in% names(.xargs)){
      data <- checkTubeData(data, x=.xargs$facet, n.x=2,
                            if.err = "stop<<ggplotTubeShell>>facet")
    }

    #don't need this if no facet plotting to worry about...
    if(!"facet.type" %in% names(.xargs)){
      .xargs$facet.type <- "wrap"
    } else {
      check <- c("wrap", "grid", "grid.col", "grid.row")
      if(!.xargs$facet.type %in% check){
        warning("bad facet.type resetting to wrap")
        .xargs$facet.type <- "wrap"
      }
    }

    #main ggplot shell build
    plt <- ggplot2::ggplot(data, ggplot2::aes(x=.data[[x]],
                                              y=.data[[y]]))

    #######################################################################
    # to think about ....
    #    what is being mapped....
    #        could automate this
    #             BUT some are not standard
    #                   col => colour
    #                   might want to make following optional?
    #                        col = group if group there and col is
    #    the not-mapped stuff needs to go into the layers ...
    #         that needs to be handled post-layer-addition ...
    #             maybe a ggplotShellLocalReset()
    #                with defaults and forced options...

    #group
    if("group" %in% map.args){
      #plt$mapping$group <- rlang::parse_quo(.xargs$group, env=environment())
      plt$mapping$group <- getTubeX(data, .xargs$group)
######################
# this might be better
# in the local plot code for
# the testTube... functions
######################
      if(!"colour" %in% map.args & !"colour" %in% names(.xargs)){
        #plt$mapping$colour <- rlang::parse_quo(.xargs$group, env=environment())
        plt$mapping$colour <- getTubeX(data, .xargs$group)
      }
    }

    if("colour" %in% map.args & "colour" %in% names(.xargs)){
      if(.xargs.test$colour=="data"){
        #plt$mapping$colour <- rlang::parse_quo(.xargs$col, env=environment())
        plt$mapping$colour <- getTubeX(data, .xargs$colour)
      }
    }
    if("size" %in% map.args & "size" %in% names(.xargs)){
      if(.xargs.test$size=="data"){
        #plt$mapping$size <- rlang::parse_quo(.xargs$size, env=environment())
        plt$mapping$size <- getTubeX(data, .xargs$size)
      }
    }

    #######################################################################

    #facet
    if("facet" %in% names(.xargs)){
      ## facet.type choices limited earlier
      #####################
      #tesing
      # passing just ggplot2::facet... args forward
      # names(formals(ggplot2::facet_grid)), etc....
      # if you give it facet, rows or cols
      #     these will override as well
      # does the job but code is messy...
      #####################
      ..xargs <- if(.xargs$facet.type=="wrap"){
        .xargs[names(.xargs) %in% names(formals(ggplot2::facet_wrap))]
      } else {
        #most be a facet_grid
        .xargs[names(.xargs) %in% names(formals(ggplot2::facet_grid))]
      }
      if(length(.xargs$facet)== 1){
        if(.xargs$facet.type=="wrap"){
          ..xargs <- modifyList(list(facets=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_wrap, ..xargs)
          #plt <- plt + ggplot2::facet_wrap(facets=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
        if(.xargs$facet.type %in% c("grid", "grid.row")){
          ..xargs <- modifyList(list(rows=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_grid, ..xargs)
          #plt <- plt + ggplot2::facet_grid(rows=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
        if(.xargs$facet.type %in% c("grid.col")){
          ..xargs <- modifyList(list(cols=ggplot2::vars(.data[[.xargs$facet[1]]])),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_grid, ..xargs)
          #plt <- plt + ggplot2::facet_grid(cols=ggplot2::vars(.data[[.xargs$facet[1]]]))
        }
      } else{
        if(.xargs$facet.type %in% c("wrap")){
          ..xargs <- modifyList(list(facets=c(ggplot2::vars(.data[[.xargs$facet[1]]]),
                                              ggplot2::vars(.data[[.xargs$facet[2]]]))),
                                ..xargs)
          plt <- plt + do.call(ggplot2::facet_wrap, ..xargs)
          #plt <- plt + ggplot2::facet_wrap(facets=c(ggplot2::vars(.data[[.xargs$facet[1]]]),
          #                                 ggplot2::vars(.data[[.xargs$facet[2]]])))
        }
        if(.xargs$facet.type %in% c("grid", "grid.row")){
          plt <- plt + ggplot2::facet_grid(rows=ggplot2::vars(.data[[.xargs$facet[1]]]),
                                           cols=ggplot2::vars(.data[[.xargs$facet[2]]]))
        }
        if(.xargs$facet.type %in% c("grid.col")){
          plt <- plt + ggplot2::facet_grid(cols=ggplot2::vars(.data[[.xargs$facet[1]]]),
                                           rows=ggplot2::vars(.data[[.xargs$facet[2]]]))
        }
      }
    }

    #palette
    ############################
    # note
    ############################
    #   testing a colouring option
    #      alpha control limited at moment
    #      NB:need to make any changes for palette/colour and fill.palette/fill
    ############################
    #test for map-able fills
    .tt <- names(.xargs.test[.xargs.test=="data"])
    .tt <- c(.tt[.tt %in% c("col", "color", "colour")],
             grep("[.]col|[.]color|[.]colour", .tt, value=TRUE))
    .pp <- c()
    if(length(.tt)>0) {
      .pp <- getTubeX(data, .xargs[[.tt[1]]])
    }
    if(!"palette" %in% names(.xargs) & length(.pp)>0){
      .xargs$palette <- if(is.numeric(.pp)){
        c("#132B43", "#56B1F7")
      } else {
        if(length(unique(.pp)) > length(.xargs$fill.palette)){
          colorRampPalette(1:5)(length(unique(.pp)))
        } else{
          1:5
        }
      }

    }
    if("palette" %in% names(.xargs)){
      # colours might not be being mapped
      .value <- if("alpha" %in% names(.xargs)){
        ggplot2::alpha(.xargs$palette, .xargs$alpha)
      } else {
        .xargs$palette
      }
      if(length(.pp)==0){
        ###########################
        # testing removing - same in fill.palette
        ##plt$mapping$colour <- "default"
        plt <- plt + ggplot2::scale_color_manual(values=.value,
                                                 guide="none")
      } else {
        #.pp <- data[[rlang::as_label(plt$mapping$colour)]]
        #.pp <- plt$mapping$colour
        if(is.numeric(.pp)){
          plt <- plt + ggplot2::scale_color_gradientn(colours=.value)
        } else {
          if(length(unique(.pp)) > length(.value)){
            .values <- colorRampPalette(.value)(length(unique(.pp)))
          }
          plt <- plt + ggplot2::scale_color_manual(values=.value)
        }
      }
    }

    #fill.palette
    ############################
    # note
    ############################
    #   testing a colouring option
    #      alpha control limited at moment
    #      NB:need to make any changes for palette/colour and fill.palette/fill
    ############################

    #test for map-able fills
    .tt <- names(.xargs.test[.xargs.test=="data"])
    .tt <- c(.tt[.tt=="fill"], grep("[.]fill", .tt, value=TRUE))
    .pp <- c()
    if(length(.tt)>0) {
      .pp <- getTubeX(data, .xargs[[.tt[1]]])
    }
    if("palette" %in% names(.xargs) & ! "fill.palette" %in% names(.xargs)){
      .xargs$fill.palette <- .xargs$palette
    }
    if(!"fill.palette" %in% names(.xargs) & length(.pp)>0){
      .xargs$fill.palette <- if(is.numeric(.pp)){
         c("#132B43", "#56B1F7")
      } else {
        if(length(unique(.pp)) > length(.xargs$fill.palette)){
          colorRampPalette(1:5)(length(unique(.pp)))
        } else{
          1:5
        }
      }

    }
    if("fill.palette" %in% names(.xargs)){
      .value <- if("alpha" %in% names(.xargs)){
        # NB: alpha just updates, not a multiple,
        #     alpha(alpha(cols, 0.5), 0.5) == alpha(cols, 0.5)
        ggplot2::alpha(.xargs$fill.palette, .xargs$alpha)
      } else {
        .xargs$fill.palette
      }
      # like colours might not be being mapped
      # could also be a [whatever].fill
      if(length(.pp)==0){
        #############################################
        # testing removing - same in fill.palette
        ##plt$mapping$fill <- "default"
        plt <- plt + ggplot2::scale_fill_manual(values=.value,
                                                guide="none")
      } else {
        #.pp <- data[[rlang::as_label(plt$mapping$colour)]]
        #.pp <- plt$mapping$colour
        .pp <- getTubeX(data, .xargs[[.tt[1]]])
        if(is.numeric(.pp)){
          plt <- plt + ggplot2::scale_fill_gradientn(colours=.value)
        } else {
          if(length(unique(.pp)) > length(.xargs$fill.palette)){
            .value <- colorRampPalette(.xargs$.value)(length(unique(.pp)))
          }
          plt <- plt + ggplot2::scale_fill_manual(values=.value)
        }
      }
    }



#########################
#force legend together if multiple are mapped
#messy.... should only be if mapped to the same arg...
########################
    if(length(names(.xargs)[names(.xargs) %in% c("colour", "size", "fill")]) >1){
      if("colour" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(colour=ggplot2::guide_legend())
      }
      if("size" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(size=ggplot2::guide_legend())
      }
      if("fill" %in% names(.xargs)){
        plt <- plt + ggplot2::guides(fill=ggplot2::guide_legend())
      }

    }

    plt <- plt +
      ggplot2::xlab(.xargs$xlab) +
      ggplot2::ylab(.xargs$ylab) +
      ggplot2::theme_bw() +
      ggplot2::theme(strip.background = ggplot2::element_rect(fill="transparent"))
    if("auto.text" %in% names(.xargs) && .xargs$auto.text){
      ###########################
      #note
      ###########################
      # following may need expanding to other plot labels
      #     strip, scale, etc ???
      plt <- plt +  ggplot2::theme(axis.title.x = ggtext::element_markdown(),
                                   axis.title.y = ggtext::element_markdown())
    }
    if("rotate.x.axes" %in% names(.xargs)){
      if(is.logical(.xargs$rotate.x.axes) && .xargs$rotate.x.axes){
        .xargs$rotate.x.axes <- 90
      }
      if(is.numeric(.xargs$rotate.x.axes)){
        # to do
        # tidy vjust and hjust if not 90
        plt <- plt + ggplot2::theme(axis.text.x = ggtext::element_markdown(angle=.xargs$rotate.x.axes[1],
                                                                           vjust=0.5, hjust=1))
      }
    }
    if(any(c("key.position", "key.direction") %in% names(.xargs))){
      # to do
      # guessing this might want tidying???
      plt <- plt + ggplot2::theme(legend.position = .xargs$key.position,
                                  legend.direction = .xargs$key.direction)
    }
    return(plt)

  }

